services:
  api:
    build:
      context: .
    container_name: fitcha_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fitcha-network

  db:
    image: postgres:17
    container_name: fitcha_postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - fitcha_data:/var/lib/postgresql/data
    networks:
      - fitcha-network

volumes:
  fitcha_data:

networks:
  fitcha-network:
  local:
    external: true
