spring.application.name=fitchaadmin

spring.config.import=optional:file:./.env[.properties]

server.port=${SERVER_PORT:8081}

spring.datasource.url=${ADMIN_DB_URL}
spring.datasource.username=${ADMIN_DB_USER}
spring.datasource.password=${ADMIN_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false