import type { TranslationDictionary } from "./index";

export const enUS: TranslationDictionary = {
    "app.tagline": "Your digital workout log",
    "common.or": "or",
    "common.actions.back": "Back",
    "common.actions.close": "Close",
    "common.actions.continue": "Continue",
    "common.actions.enter": "Sign in",
    "common.actions.createAccount": "Create account",
    "common.actions.understand": "Got it",
    "common.actions.cancel": "Cancel",
    "common.actions.confirm": "Confirm",
    "common.actions.add": "Add",
    "common.actions.next": "Next",
    "common.actions.finish": "Finish",
    "common.actions.finishWorkout": "Finish workout",
    "common.actions.remove": "Remove",
    "common.actions.startWorkout": "Start workout",
    "common.units.cm": "cm",
    "common.units.kg": "kg",
    "common.relative.today": "today",
    "common.relative.yesterday": "yesterday",
    "common.relative.daysAgo": "{count} days ago",
    "common.relative.weekAgo": "1 week",
    "common.relative.weeksAgo": "{count} weeks",
    "common.days.sunday": "Sunday",
    "common.days.monday": "Monday",
    "common.days.tuesday": "Tuesday",
    "common.days.wednesday": "Wednesday",
    "common.days.thursday": "Thursday",
    "common.days.friday": "Friday",
    "common.days.saturday": "Saturday",
    "common.daysShort.sunday": "Sun",
    "common.daysShort.monday": "Mon",
    "common.daysShort.tuesday": "Tue",
    "common.daysShort.wednesday": "Wed",
    "common.daysShort.thursday": "Thu",
    "common.daysShort.friday": "Fri",
    "common.daysShort.saturday": "Sat",
    "auth.login.emailLabel": "Email",
    "auth.login.emailPlaceholder": "you@email.com",
    "auth.login.passwordLabel": "Password",
    "auth.login.passwordPlaceholder": "********",
    "auth.login.submit": "Sign in",
    "auth.login.submitting": "Signing in...",
    "auth.login.forgotPasswordCta": "Forgot password?",
    "auth.login.createAccountCta": "Create account",
    "auth.register.title": "Create account",
    "auth.register.subtitle": "Fill in your details to get started",
    "auth.register.nameLabel": "Name",
    "auth.register.namePlaceholder": "Your name",
    "auth.register.emailLabel": "Email",
    "auth.register.emailPlaceholder": "you@email.com",
    "auth.register.passwordLabel": "Password",
    "auth.register.passwordPlaceholder": "Minimum 6 characters",
    "auth.register.confirmPasswordLabel": "Confirm password",
    "auth.register.confirmPasswordPlaceholder": "Repeat your password",
    "auth.register.submit": "Create account",
    "auth.register.submitting": "Creating account...",
    "auth.register.hasAccountPrefix": "Already have an account?",
    "auth.validation.nameRequired": "Enter your name",
    "auth.validation.emailRequired": "Enter your email",
    "auth.validation.emailInvalid": "Invalid email",
    "auth.validation.passwordRequired": "Enter your password",
    "auth.validation.passwordCreateRequired": "Enter a password",
    "auth.validation.passwordMin": "Minimum of 6 characters",
    "auth.validation.confirmPasswordRequired": "Confirm your password",
    "auth.validation.passwordMismatch": "Passwords do not match",
    "auth.errors.invalidCredentials": "Incorrect email or password",
    "auth.errors.emailAlreadyExists": "This email is already in use",
    "auth.errors.emailNotVerified": "Verify your email before signing in",
    "auth.errors.currentPasswordInvalid": "The current password is incorrect",
    "auth.errors.genericLogin": "Unable to sign in",
    "auth.errors.genericRegister": "Unable to create the account",
    "auth.errors.serviceUnavailableTitle": "Service unavailable",
    "auth.errors.serviceUnavailableMessage":
        "The service may be unavailable right now. Please try again in a moment.",
    "auth.sessionExpired.title": "Session expired",
    "auth.sessionExpired.message":
        "Your access expired while the app was closed. Sign in again to continue.",
    "auth.resetPassword.title": "Recover access",
    "auth.resetPassword.description":
        "Enter your email and we will send a link so you can reset your password.",
    "auth.resetPassword.submit": "Send link",
    "auth.resetPassword.submitting": "Sending...",
    "auth.resetPassword.successTitle": "Check your email",
    "auth.resetPassword.successMessage":
        "If an account exists for {email}, we will send a link so you can reset your password.",
    "auth.resetPassword.error": "Unable to send the reset link",
    "auth.register.successTitle": "Check your email",
    "auth.register.successMessage":
        "Your account has been created. We sent a verification link to {email}. After that, come back to the app and sign in.",
    "navigation.profile": "Profile",
    "navigation.machineDetail": "Detail",
    "profile.kicker": "profile",
    "profile.header.description":
        "Review the authenticated account details and manage your credit balance for AI workout generation.",
    "profile.account.title": "Account",
    "profile.account.description":
        "Name and email reflect the account authenticated in the backend.",
    "profile.language.title": "App language",
    "profile.language.description":
        "Choose the default language saved on this device. Already migrated screens update immediately.",
    "profile.credits.title": "Fitcha AI credits",
    "profile.credits.subtitle": "1 credit = 1 custom workout",
    "profile.credits.description":
        "Buy single credits via Pix. Your balance is released automatically as soon as the payment is approved.",
    "profile.credits.balanceLabel": "Available credits",
    "profile.credits.balanceHint": "Each completed generation consumes 1 credit.",
    "profile.credits.pendingTitle": "Payment pending",
    "profile.credits.pendingDescriptionWithDate":
        "There is a Pix for {quantity} credit(s) waiting for payment until {date}.",
    "profile.credits.pendingDescription":
        "There is a Pix waiting for payment to release more credits.",
    "profile.credits.continuePayment": "Continue payment",
    "profile.credits.buy": "Buy credits",
    "profile.form.title": "Security",
    "profile.form.description": "Change your real account password.",
    "profile.form.currentPasswordLabel": "Current password",
    "profile.form.currentPasswordPlaceholder": "Enter your current password",
    "profile.form.currentPasswordRequired": "Enter your current password",
    "profile.form.newPasswordRequired": "Enter a new password",
    "profile.form.newPasswordLabel": "New password",
    "profile.form.newPasswordPlaceholder": "Minimum 6 characters",
    "profile.form.confirmNewPasswordLabel": "Confirm new password",
    "profile.form.confirmNewPasswordPlaceholder": "Repeat the new password",
    "profile.form.save": "Update password",
    "profile.form.saving": "Saving...",
    "profile.form.saveError": "Unable to update the password",
    "profile.alert.savedTitle": "Password updated",
    "profile.alert.savedMessage": "Your password was updated successfully.",
    "creditCheckout.title": "Buy credits",
    "creditCheckout.description":
        "Pay with Pix and receive credits to generate custom AI workouts in Fitcha.",
    "creditCheckout.step.quantity": "Quantity",
    "creditCheckout.step.document": "CPF",
    "creditCheckout.step.payment": "Pix",
    "creditCheckout.quantityTitle": "How many credits do you want to buy?",
    "creditCheckout.quantityDescription": "Each credit unlocks 1 new AI workout generation.",
    "creditCheckout.quantityLabel": "Credit quantity",
    "creditCheckout.quantityPlaceholder": "1",
    "creditCheckout.quantityHint": "Each credit costs {price}. Estimated total: {total}.",
    "creditCheckout.documentTitle": "Enter the payer CPF",
    "creditCheckout.documentDescription":
        "We use the CPF only to generate the Pix charge in Mercado Pago.",
    "creditCheckout.documentLabel": "Payer CPF",
    "creditCheckout.documentPlaceholder": "00000000000",
    "creditCheckout.generatePix": "Generate Pix",
    "creditCheckout.generatingPix": "Generating Pix...",
    "creditCheckout.paymentFallback": "Fitcha AI credit purchase",
    "creditCheckout.summaryCredits": "{count} credit(s)",
    "creditCheckout.status.paid": "Paid",
    "creditCheckout.status.awaitingPix": "Waiting for Pix",
    "creditCheckout.status.pending": "Pending",
    "creditCheckout.pixValidUntil": "Pix valid until {date}.",
    "creditCheckout.copyPastePix": "Pix copy and paste",
    "creditCheckout.approvedMessage":
        "Payment confirmed. Your credits are already available in the app.",
    "creditCheckout.checkPayment": "Check payment",
    "creditCheckout.openCharge": "Open charge",
    "creditCheckout.error.loadSummary": "Unable to load your credits",
    "creditCheckout.error.invalidQuantity": "Enter a valid credit quantity",
    "creditCheckout.error.invalidCpf": "Enter a valid CPF with 11 digits",
    "creditCheckout.error.generatePix": "Unable to generate the Pix",
    "aiWizard.noCredits.title": "You are out of credits",
    "aiWizard.noCredits.description":
        "Each AI-generated workout consumes 1 credit. Buy credits to continue.",
    "aiWizard.noCredits.buy": "Buy credits",
    "categories.peito": "Chest",
    "categories.costas": "Back",
    "categories.pernas": "Legs",
    "categories.ombros": "Shoulders",
    "categories.biceps": "Biceps",
    "categories.triceps": "Triceps",
    "categories.core": "Core",
    "categories.cardio": "Cardio",
    "addMachine.title": "New machine",
    "addMachine.nameLabel": "name",
    "addMachine.namePlaceholder": "Ex.: bench press",
    "addMachine.descriptionLabel": "description (optional)",
    "addMachine.descriptionPlaceholder": "Exercise details...",
    "addMachine.categoryLabel": "category",
    "addMachine.allCategories": "all",
    "addMachine.searchLabel": "search",
    "addMachine.searchPlaceholder": "Type the machine name or alias",
    "addMachine.loading": "Loading catalog...",
    "addMachine.emptyTitle": "No machines found",
    "addMachine.emptyMessage": "Try another term or adjust the category filter.",
    "week.title": "Your week",
    "week.todayBadge": "TODAY",
    "week.emptyDay": "No planned machines yet.",
    "week.machineCount": "{count} machine{pluralSuffix}",
    "week.generated.title": "Workout generated",
    "week.generated.message":
        "Your automatic workout was created successfully and replaced the current week.",
    "day.machineCount": "{count} machine{pluralSuffix}",
    "day.addButton": "Add machine",
    "day.maxWeight": "max {weight}kg",
    "day.remove.title": "Remove machine",
    "day.remove.message":
        'Remove "{name}" from this day? History will be kept if it is still in another day.',
    "detail.permission.title": "Permission required",
    "detail.permission.galleryMessage": "Allow gallery access to choose a photo for this machine.",
    "detail.permission.cameraMessage": "Allow camera access to take a photo of this machine.",
    "detail.photo.add": "Add photo",
    "detail.photo.change": "Change photo",
    "detail.photo.sourceMessage": "Choose where the image should come from.",
    "detail.photo.useCamera": "Use camera",
    "detail.photo.chooseGallery": "Choose from gallery",
    "detail.photo.removeTitle": "Remove photo?",
    "detail.photo.removeMessage": "The current image will be removed from this machine.",
    "detail.photo.removeAction": "Remove photo",
    "detail.photo.actionsTitle": "Machine photo",
    "detail.photo.actionsMessage": "Choose what you want to do with the image.",
    "detail.record.title": "record",
    "detail.record.subtitle": "3-set sequence with the highest saved volume for this machine.",
    "detail.record.empty": "There is no saved record for this machine yet.",
    "detail.record.volume": "volume {volume}kg",
    "detail.history.title": "history",
    "detail.history.empty": "No records yet. Start a workout to log weights.",
    "home.greetingFallback": "athlete",
    "home.delta.noBase": "No baseline",
    "home.delta.zero": "0 kg",
    "home.relative.daysAgo": "{count} days",
    "home.featured.emptyTitle": "progress by machine",
    "home.featured.emptySubtitle": "Set up your week to unlock this comparison for each exercise.",
    "home.featured.todayTitle": "today's machines",
    "home.featured.todaySubtitle": "Swipe sideways to see load progress for each machine.",
    "home.featured.nextTitle": "next workout - {day}",
    "home.featured.nextSubtitle":
        "There are no planned machines for today, so the comparison uses the next active day.",
    "home.featured.focusCount": "{count} machine{pluralSuffix} in focus",
    "home.featured.noPlannedDays": "No planned day yet",
    "home.featured.emptyPanel":
        "Open Week, spread machines across your days, and this area will start showing progress for each one.",
    "home.machine.comparison.noHistory": "There is no saved workout for this machine yet.",
    "home.machine.comparison.needMore": "Save one more workout to compare your progress.",
    "home.machine.comparison.default": "Current load compared with the first saved record.",
    "home.machine.previous.noHistory": "no history",
    "home.machine.previous.oneRecord": "1 saved record",
    "home.machine.previous.noComparison": "no comparison",
    "home.machine.previous.vsLast": "{value} vs. last workout",
    "home.machine.lastTrained": "last {label}",
    "home.machine.noTraining": "no workout",
    "home.machine.metric.current": "current",
    "home.machine.metric.initial": "initial",
    "home.machine.metric.record": "record",
    "home.machine.recordVolume": "{volume} volume",
    "home.machine.noHistoryCard":
        "This machine is already planned for the day, but it still has no saved history.",
    "home.machine.recordsTitle": "latest records",
    "home.header.kicker": "home dashboard",
    "home.header.greeting": "Hi, {name}",
    "home.header.summaryWithHistory":
        "Current streak of {streak} day{streakSuffix} and {recent} active day{recentSuffix} in the last 7 days.",
    "home.header.summaryWithoutHistory":
        "You can already organize your week here, but the analysis gets much better after the first saved workout.",
    "home.header.lastWorkout": "last workout",
    "home.header.nextTarget": "next target",
    "home.header.noRecord": "no record",
    "home.header.buildWeek": "build your week",
    "home.header.openWeek": "Open week",
    "home.stats.streakTitle": "Streak",
    "home.stats.streakHint": "days in a row{suffix}",
    "home.stats.streakHintZero": " for now",
    "home.stats.last7Title": "Last 7 days",
    "home.stats.last7Hint": "days with saved workouts",
    "home.stats.monthTitle": "This month",
    "home.stats.monthHint": "days going to the gym",
    "home.stats.weekTitle": "Week",
    "home.stats.weekHint": "{count} planned machine{pluralSuffix}",
    "home.rhythm.kicker": "weekly rhythm",
    "home.rhythm.titleWithCount": "{count} day{daySuffix} already planned",
    "home.rhythm.titleEmpty": "Your week is still empty",
    "home.rhythm.subtitleWithNext": "Next commitment: {next}.",
    "home.rhythm.subtitleEmpty":
        "Open Week to set up the days, machines, and categories you want to follow.",
    "home.nextPlanned.today": "Today - {count} machine{pluralSuffix}",
    "home.nextPlanned.tomorrow": "Tomorrow - {count} machine{pluralSuffix}",
    "home.nextPlanned.other": "{day} - {count} machine{pluralSuffix}",
    "aiWizard.badge": "workout with AI",
    "aiWizard.step.body": "Your body data",
    "aiWizard.step.days": "Which days will you train?",
    "aiWizard.step.preferences": "Workout preferences",
    "aiWizard.step.intensity": "What intensity?",
    "aiWizard.step.goal": "What is your goal?",
    "aiWizard.step.instructions": "Custom instructions",
    "aiWizard.step.review": "Confirm generation",
    "aiWizard.actions.generate": "Generate workout",
    "aiWizard.actions.generating": "Generating...",
    "aiWizard.error.title": "Error generating workout",
    "aiWizard.error.message": "Unable to generate the workout right now.",
    "aiWizard.body.heightLabel": "Height (cm)",
    "aiWizard.body.weightLabel": "Weight (kg)",
    "aiWizard.body.hint": "These values help calibrate the suggested loads.",
    "aiWizard.days.description":
        "Mark the exact days you want to go to the gym. AI will use that to build a more precise split.",
    "aiWizard.days.empty": "Select at least one day.",
    "aiWizard.days.selectedCount": "{count} day{daySuffix} selected{selectedSuffix}.",
    "aiWizard.preferences.description":
        "These fields are optional. Fill them in if you want AI to respect a time cap, daily volume, or a specific split model.",
    "aiWizard.preferences.hoursLabel": "Hours per day",
    "aiWizard.preferences.hoursPlaceholder": "Ex.: 1, 1.5 or 2",
    "aiWizard.preferences.machinesLabel": "Machines per day",
    "aiWizard.preferences.machinesPlaceholder": "Ex.: 6",
    "aiWizard.preferences.splitLabel": "Split model",
    "aiWizard.preferences.splitPlaceholder": "Ex.: ABC, ABCAB, fullbody",
    "aiWizard.intensity.light.title": "light",
    "aiWizard.intensity.light.description": "Beginner or returning",
    "aiWizard.intensity.moderate.title": "moderate",
    "aiWizard.intensity.moderate.description": "Consistent training",
    "aiWizard.intensity.intense.title": "intense",
    "aiWizard.intensity.intense.description": "High volume and load",
    "aiWizard.goal.hypertrophy.title": "hypertrophy",
    "aiWizard.goal.hypertrophy.description": "Muscle gain",
    "aiWizard.goal.strength.title": "strength",
    "aiWizard.goal.strength.description": "Higher max load",
    "aiWizard.goal.endurance.title": "endurance",
    "aiWizard.goal.endurance.description": "More reps and stamina",
    "aiWizard.goal.weightLoss.title": "weight loss",
    "aiWizard.goal.weightLoss.description": "Fat loss with training",
    "aiWizard.instructions.description":
        "Add notes for the AI, such as injuries, exercises you want to avoid, focus on a muscle group, or equipment available at your gym.",
    "aiWizard.instructions.placeholder":
        "Ex.: avoid free squats because of knee pain and prioritize machines.",
    "aiWizard.review.title": "generation summary",
    "aiWizard.review.height": "Height",
    "aiWizard.review.weight": "Weight",
    "aiWizard.review.selectedDays": "Selected days",
    "aiWizard.review.totalDays": "Total days",
    "aiWizard.review.hoursPerDay": "Hours per day",
    "aiWizard.review.machinesPerDay": "Machines per day",
    "aiWizard.review.split": "Split model",
    "aiWizard.review.intensity": "Intensity",
    "aiWizard.review.goal": "Goal",
    "aiWizard.review.instructions": "Custom instructions",
    "aiWizard.review.notInformed": "Not informed",
    "aiWizard.review.noSpecificSplit": "No specific split",
    "aiWizard.review.noAdditionalNotes": "No additional notes.",
    "aiWizard.review.promptNote":
        "The final prompt is now assembled only in the backend before calling the AI.",
    "workout.saved.title": "Workout finished!",
    "workout.saved.message":
        "{count} machine{machineSuffix} recorded{registeredSuffix} in {elapsed}",
    "workout.empty.title": "Empty workout",
    "workout.empty.message": "No weights were recorded.",
    "workout.error.title": "Save error",
    "workout.error.message": "Unable to save the workout right now. Please try again shortly.",
    "workout.incomplete.title": "No complete machine",
    "workout.incomplete.message":
        "There is still no exercise with all 3 sets completed. If you leave now, your drafts will be discarded.",
    "workout.incomplete.confirm": "Leave without saving",
    "workout.pending.title": "Finish with pending sets?",
    "workout.pending.message":
        "{count} machine{machineSuffix} without all 3 sets completed. You can save now or keep reviewing.",
    "workout.quit.title": "Quit workout?",
    "workout.quit.message": "If you leave now, the workout will end and nothing will be saved.",
    "workout.quit.confirm": "Quit",
    "workout.series.one": "Set 1",
    "workout.series.two": "Set 2",
    "workout.series.three": "Set 3",
    "workout.position": "{current} of {total}",
    "workout.completedProgress": "{completed}/{total} complete",
    "workout.swapHint":
        "Use the arrows or tap the cards to switch machines without losing your drafts.",
    "workout.status.registeredTitle": "Exercise logged",
    "workout.status.draftTitle": "Draft saved",
    "workout.status.skipTitle": "You can skip without breaking the flow",
    "workout.status.registeredMessage":
        "You can move on now or come back later to adjust the weights.",
    "workout.status.draftMessage":
        "Values stay saved when switching machines. Finish it when the machine is free.",
    "workout.status.skipMessage":
        "If the machine is busy, move on now and come back whenever you want using the cards above.",
    "workout.rest.title": "rest",
    "workout.rest.idle": "The timer starts as soon as you confirm a set.",
    "workout.rest.active": "Counting since the last confirmed set.",
    "workout.fillSeries": "fill in and confirm all 3 sets",
    "workout.series.confirmCta": "Confirm",
    "workout.series.confirmedCta": "Confirmed",
    "workout.series.readyState": "Ready",
    "workout.series.lockedState": "Locked",
    "workout.series.confirmedState": "Confirmed",
    "workout.series.lockedHint": "Confirm the previous set to unlock the next one.",
    "workout.nextMachine": "Next machine",
    "services.aiWorkout.generateError": "Unable to generate the workout automatically",
    "services.days.loadError": "Unable to load the days",
    "services.days.addError": "Unable to add the machine",
    "services.days.removeError": "Unable to remove the machine",
    "services.days.replaceError": "Unable to replace the week",
    "services.machines.loadError": "Unable to load the machines",
    "services.machines.updateError": "Unable to update the machine",
    "services.history.loadError": "Unable to load the history",
    "services.history.saveError": "Unable to save the workout",
    "services.credit.loadError": "Unable to load your credits",
    "services.credit.checkoutError": "Unable to generate the Pix",
    "services.axios.missingApiUrl": "Set EXPO_PUBLIC_API_URL in frontend/.env",
    "notifications.emulatorUnsupported": "Notifications do not work on the emulator",
    "notifications.channelName": "Workout reminders",
    "notifications.message1.title": "Let's train! 💪",
    "notifications.message1.body": "Today is {categories} day. Don't leave it for tomorrow!",
    "notifications.message2.title": "Gym time! 🏋️",
    "notifications.message2.body": "Your {categories} workout is waiting for you.",
    "notifications.message3.title": "It's time! ⚡",
    "notifications.message3.body": "{categories} day. Time to load the bar!",
    "notifications.message4.title": "Workout of the day 🔥",
    "notifications.message4.body": "{categories} is on today's menu. See you at the gym!",
    "notifications.message5.title": "Don't skip your workout! 💪",
    "notifications.message5.body": "Today you have {categories}. Your body will thank you.",
};
