import type { TranslationDictionary } from "./index";

export const enUS: TranslationDictionary = {
    "app.tagline": "Your digital workout log",
    "common.or": "or",
    "common.actions.back": "Back",
    "common.actions.close": "Close",
    "common.actions.enter": "Sign in",
    "common.actions.createAccount": "Create account",
    "common.actions.understand": "Got it",
    "auth.login.emailLabel": "Email",
    "auth.login.emailPlaceholder": "you@email.com",
    "auth.login.passwordLabel": "Password",
    "auth.login.passwordPlaceholder": "********",
    "auth.login.submit": "Sign in",
    "auth.login.submitting": "Signing in...",
    "auth.login.createAccountCta": "Create account",
    "auth.register.title": "Create account",
    "auth.register.subtitle": "Fill in your details to get started",
    "auth.register.nameLabel": "Name",
    "auth.register.namePlaceholder": "Your name",
    "auth.register.emailLabel": "Email",
    "auth.register.emailPlaceholder": "you@email.com",
    "auth.register.passwordLabel": "Password",
    "auth.register.passwordPlaceholder": "Minimum 6 characters",
    "auth.register.confirmPasswordLabel": "Confirm password",
    "auth.register.confirmPasswordPlaceholder": "Repeat your password",
    "auth.register.submit": "Create account",
    "auth.register.submitting": "Creating account...",
    "auth.register.hasAccountPrefix": "Already have an account?",
    "auth.validation.nameRequired": "Enter your name",
    "auth.validation.emailRequired": "Enter your email",
    "auth.validation.emailInvalid": "Invalid email",
    "auth.validation.passwordRequired": "Enter your password",
    "auth.validation.passwordCreateRequired": "Enter a password",
    "auth.validation.passwordMin": "Minimum of 6 characters",
    "auth.validation.confirmPasswordRequired": "Confirm your password",
    "auth.validation.passwordMismatch": "Passwords do not match",
    "auth.errors.invalidCredentials": "Incorrect email or password",
    "auth.errors.emailAlreadyExists": "This email is already in use",
    "auth.errors.genericLogin": "Unable to sign in",
    "auth.errors.genericRegister": "Unable to create the account",
    "auth.errors.serviceUnavailableTitle": "Service unavailable",
    "auth.errors.serviceUnavailableMessage":
        "The service may be unavailable right now. Please try again in a moment.",
    "navigation.profile": "Profile",
    "profile.kicker": "profile",
    "profile.header.description":
        "Adjust your name, email, and password locally and track the subscription that unlocks AI mode.",
    "profile.language.title": "App language",
    "profile.language.description":
        "Choose the default language saved on this device. Already migrated screens update immediately.",
    "profile.ai.subtitle": "Monthly plan paid via Pix",
    "profile.ai.status.active": "Active",
    "profile.ai.status.inactive": "Inactive",
    "profile.ai.description":
        "AI access is enabled automatically when the Pix payment is approved and remains active for 1 month.",
    "profile.ai.benefit.assistantButton":
        "Unlocks the AI workout assistant button on the home screen.",
    "profile.ai.benefit.autoActivation":
        "Automatic activation as soon as Mercado Pago confirms the Pix.",
    "profile.ai.benefit.accessWindow":
        "Guaranteed access for 1 month with no manual cancellation during the active period.",
    "profile.ai.activeTitle": "Plan active",
    "profile.ai.activeDescriptionWithDate":
        "Valid until {date}. During this period there is no manual cancellation option.",
    "profile.ai.activeDescription": "Your AI access has already been enabled in the app.",
    "profile.ai.pendingTitle": "Payment pending",
    "profile.ai.pendingDescriptionWithDate":
        "There is a Pix waiting for payment until {date}.",
    "profile.ai.pendingDescription":
        "There is a Pix waiting for payment to activate AI mode.",
    "profile.ai.continuePayment": "Continue payment",
    "profile.ai.subscribe": "Subscribe to AI plan",
    "profile.form.title": "Your details",
    "profile.form.description": "These changes are still stored locally in the frontend for now.",
    "profile.form.newPasswordLabel": "New password",
    "profile.form.newPasswordPlaceholder": "Change only if you want",
    "profile.form.confirmNewPasswordLabel": "Confirm new password",
    "profile.form.confirmNewPasswordPlaceholder": "Repeat the new password",
    "profile.form.save": "Save changes",
    "profile.form.saving": "Saving...",
    "profile.form.saveError": "Unable to save the profile",
    "profile.alert.savedTitle": "Profile saved",
    "profile.alert.savedMessage": "The changes were stored only in this frontend.",
    "planCheckout.title": "Subscribe to Fitcha AI",
    "planCheckout.description":
        "When you pay this Pix, the plan benefits stay active for 1 month. During this period AI mode remains enabled with no manual cancellation option.",
    "planCheckout.whatYouGet": "What you get",
    "planCheckout.benefit.aiAccess":
        "Access to the AI workout assistant for 1 month after payment approval.",
    "planCheckout.benefit.autoActivation":
        "Automatic activation when Mercado Pago confirms the Pix.",
    "planCheckout.benefit.renewal": "A new subscription only after the current period ends.",
    "planCheckout.documentLabel": "Payer CPF",
    "planCheckout.documentPlaceholder": "00000000000",
    "planCheckout.generatePix": "Generate Pix",
    "planCheckout.generatingPix": "Generating Pix...",
    "planCheckout.planFallback": "Fitcha AI plan",
    "planCheckout.status.paid": "Paid",
    "planCheckout.status.awaitingPix": "Waiting for Pix",
    "planCheckout.status.pending": "Pending",
    "planCheckout.pixValidUntil": "Pix valid until {date}.",
    "planCheckout.planActiveUntil": "Plan active until {date}.",
    "planCheckout.copyPastePix": "Pix copy and paste",
    "planCheckout.approvedMessage":
        "Payment confirmed. The AI button should now appear on screens where the feature is available.",
    "planCheckout.checkPayment": "Check payment",
    "planCheckout.openCharge": "Open charge",
    "planCheckout.error.loadPlan": "Unable to load the plan",
    "planCheckout.error.invalidCpf": "Enter a valid CPF with 11 digits",
    "planCheckout.error.generatePix": "Unable to generate the Pix",
};
