import type { TranslationDictionary } from './index'

export const enUS: TranslationDictionary = {
    'app.tagline': 'Your digital workout log',
    'appUpdate.title': 'New version available',
    'appUpdate.message':
        'Fitcha version {latestVersion} is now available. You are currently using version {currentVersion}.',
    'appUpdate.requiredMessage':
        'A required update is available to keep using the app. Current version: {currentVersion}. New version: {latestVersion}.',
    'appUpdate.confirm': 'Download now',
    'appUpdate.cancel': 'Later',
    'common.or': 'or',
    'common.actions.back': 'Back',
    'common.actions.close': 'Close',
    'common.actions.continue': 'Continue',
    'common.actions.enter': 'Sign in',
    'common.actions.createAccount': 'Create account',
    'common.actions.understand': 'Got it',
    'common.actions.cancel': 'Cancel',
    'common.actions.confirm': 'Confirm',
    'common.actions.add': 'Add',
    'common.actions.next': 'Next',
    'common.actions.finish': 'Finish',
    'common.actions.finishWorkout': 'Finish workout',
    'common.actions.remove': 'Remove',
    'common.actions.startWorkout': 'Start workout',
    'common.units.cm': 'cm',
    'common.units.kg': 'kg',
    'common.relative.today': 'today',
    'common.relative.yesterday': 'yesterday',
    'common.relative.daysAgo': '{count} days ago',
    'common.relative.weekAgo': '1 week',
    'common.relative.weeksAgo': '{count} weeks',
    'common.days.sunday': 'Sunday',
    'common.days.monday': 'Monday',
    'common.days.tuesday': 'Tuesday',
    'common.days.wednesday': 'Wednesday',
    'common.days.thursday': 'Thursday',
    'common.days.friday': 'Friday',
    'common.days.saturday': 'Saturday',
    'common.daysShort.sunday': 'Sun',
    'common.daysShort.monday': 'Mon',
    'common.daysShort.tuesday': 'Tue',
    'common.daysShort.wednesday': 'Wed',
    'common.daysShort.thursday': 'Thu',
    'common.daysShort.friday': 'Fri',
    'common.daysShort.saturday': 'Sat',
    'auth.login.emailLabel': 'Email',
    'auth.login.emailPlaceholder': 'you@email.com',
    'auth.login.passwordLabel': 'Password',
    'auth.login.passwordPlaceholder': '********',
    'auth.login.submit': 'Sign in',
    'auth.login.submitting': 'Signing in...',
    'auth.login.forgotPasswordCta': 'Forgot password?',
    'auth.login.createAccountCta': 'Create account',
    'auth.register.title': 'Create account',
    'auth.register.subtitle': 'Fill in your details to get started',
    'auth.register.nameLabel': 'Name',
    'auth.register.namePlaceholder': 'Your name',
    'auth.register.emailLabel': 'Email',
    'auth.register.emailPlaceholder': 'you@email.com',
    'auth.register.passwordLabel': 'Password',
    'auth.register.passwordPlaceholder': 'Minimum 6 characters',
    'auth.register.confirmPasswordLabel': 'Confirm password',
    'auth.register.confirmPasswordPlaceholder': 'Repeat your password',
    'auth.register.submit': 'Create account',
    'auth.register.submitting': 'Creating account...',
    'auth.register.hasAccountPrefix': 'Already have an account?',
    'auth.validation.nameRequired': 'Enter your name',
    'auth.validation.emailRequired': 'Enter your email',
    'auth.validation.emailInvalid': 'Invalid email',
    'auth.validation.passwordRequired': 'Enter your password',
    'auth.validation.passwordCreateRequired': 'Enter a password',
    'auth.validation.passwordMin': 'Minimum of 6 characters',
    'auth.validation.confirmPasswordRequired': 'Confirm your password',
    'auth.validation.passwordMismatch': 'Passwords do not match',
    'auth.errors.invalidCredentials': 'Incorrect email or password',
    'auth.errors.emailAlreadyExists': 'This email is already in use',
    'auth.errors.emailNotVerified': 'Verify your email before signing in',
    'auth.errors.currentPasswordInvalid': 'The current password is incorrect',
    'auth.errors.genericLogin': 'Unable to sign in',
    'auth.errors.genericRegister': 'Unable to create the account',
    'auth.errors.serviceUnavailableTitle': 'Service unavailable',
    'auth.errors.serviceUnavailableMessage':
        'The service may be unavailable right now. Please try again in a moment.',
    'auth.sessionExpired.title': 'Session expired',
    'auth.sessionExpired.message':
        'Your access expired while the app was closed. Sign in again to continue.',
    'auth.resetPassword.title': 'Recover access',
    'auth.resetPassword.description':
        'Enter your email and we will send a link so you can reset your password.',
    'auth.resetPassword.submit': 'Send link',
    'auth.resetPassword.submitting': 'Sending...',
    'auth.resetPassword.successTitle': 'Check your email',
    'auth.resetPassword.successMessage':
        'If an account exists for {email}, we will send a link so you can reset your password.',
    'auth.resetPassword.error': 'Unable to send the reset link',
    'auth.register.successTitle': 'Check your email',
    'auth.register.successMessage':
        'Your account has been created. We sent a verification link to {email}. After that, come back to the app and sign in.',
    'navigation.profile': 'Profile',
    'navigation.machineDetail': 'Detail',
    'profile.kicker': 'profile',
    'profile.header.description':
        'Review the authenticated account details and manage your credit balance for AI workout generation.',
    'profile.account.title': 'Account',
    'profile.account.description':
        'Name and email reflect the account authenticated in the backend.',
    'profile.language.title': 'App language',
    'profile.language.description':
        'Choose the default language saved on this device. Already migrated screens update immediately.',
    'profile.credits.title': 'Fitcha AI credits',
    'profile.credits.subtitle': '1 credit = 1 custom workout',
    'profile.credits.description':
        'Buy single credits via Pix. Your balance is released automatically as soon as the payment is approved.',
    'profile.credits.balanceLabel': 'Available credits',
    'profile.credits.balanceHint':
        'Each completed generation consumes 1 credit.',
    'profile.credits.pendingTitle': 'Payment pending',
    'profile.credits.pendingDescriptionWithDate':
        'There is a Pix for {quantity} credit(s) waiting for payment until {date}.',
    'profile.credits.pendingDescription':
        'There is a Pix waiting for payment to release more credits.',
    'profile.credits.continuePayment': 'Continue payment',
    'profile.credits.buy': 'Buy credits',
    'profile.form.title': 'Security',
    'profile.form.description': 'Change your real account password.',
    'profile.form.currentPasswordLabel': 'Current password',
    'profile.form.currentPasswordPlaceholder': 'Enter your current password',
    'profile.form.currentPasswordRequired': 'Enter your current password',
    'profile.form.newPasswordRequired': 'Enter a new password',
    'profile.form.newPasswordLabel': 'New password',
    'profile.form.newPasswordPlaceholder': 'Minimum 6 characters',
    'profile.form.confirmNewPasswordLabel': 'Confirm new password',
    'profile.form.confirmNewPasswordPlaceholder': 'Repeat the new password',
    'profile.form.save': 'Update password',
    'profile.form.saving': 'Saving...',
    'profile.form.saveError': 'Unable to update the password',
    'profile.alert.savedTitle': 'Password updated',
    'profile.alert.savedMessage': 'Your password was updated successfully.',
    'creditCheckout.title': 'Buy credits',
    'creditCheckout.description':
        'Pay with Pix and receive credits to generate custom AI workouts in Fitcha.',
    'creditCheckout.step.quantity': 'Quantity',
    'creditCheckout.step.document': 'CPF',
    'creditCheckout.step.payment': 'Pix',
    'creditCheckout.quantityTitle': 'How many credits do you want to buy?',
    'creditCheckout.quantityDescription':
        'Each credit unlocks 1 new AI workout generation.',
    'creditCheckout.quantityLabel': 'Credit quantity',
    'creditCheckout.quantityPlaceholder': '1',
    'creditCheckout.quantityHint':
        'Each credit costs {price}. Estimated total: {total}.',
    'creditCheckout.documentTitle': 'Enter the payer CPF',
    'creditCheckout.documentDescription':
        'We use the CPF only to generate the Pix charge in Mercado Pago.',
    'creditCheckout.documentLabel': 'Payer CPF',
    'creditCheckout.documentPlaceholder': '00000000000',
    'creditCheckout.generatePix': 'Generate Pix',
    'creditCheckout.generatingPix': 'Generating Pix...',
    'creditCheckout.paymentFallback': 'Fitcha AI credit purchase',
    'creditCheckout.summaryCredits': '{count} credit(s)',
    'creditCheckout.status.paid': 'Paid',
    'creditCheckout.status.awaitingPix': 'Waiting for Pix',
    'creditCheckout.status.pending': 'Pending',
    'creditCheckout.pixValidUntil': 'Pix valid until {date}.',
    'creditCheckout.copyPastePix': 'Pix copy and paste',
    'creditCheckout.approvedMessage':
        'Payment confirmed. Your credits are already available in the app.',
    'creditCheckout.checkPayment': 'Check payment',
    'creditCheckout.openCharge': 'Open charge',
    'creditCheckout.error.loadSummary': 'Unable to load your credits',
    'creditCheckout.error.invalidQuantity': 'Enter a valid credit quantity',
    'creditCheckout.error.invalidCpf': 'Enter a valid CPF with 11 digits',
    'creditCheckout.error.generatePix': 'Unable to generate the Pix',
    'aiWizard.noCredits.title': 'You are out of credits',
    'aiWizard.noCredits.description':
        'Each AI-generated workout consumes 1 credit. Buy credits to continue.',
    'aiWizard.noCredits.buy': 'Buy credits',
    'categories.peito': 'Chest',
    'categories.costas': 'Back',
    'categories.pernas': 'Legs',
    'categories.ombros': 'Shoulders',
    'categories.biceps': 'Biceps',
    'categories.triceps': 'Triceps',
    'categories.core': 'Core',
    'categories.cardio': 'Cardio',
    'addMachine.title': 'New machine',
    'addMachine.nameLabel': 'name',
    'addMachine.namePlaceholder': 'Ex.: bench press',
    'addMachine.descriptionLabel': 'description (optional)',
    'addMachine.descriptionPlaceholder': 'Exercise details...',
    'addMachine.categoryLabel': 'category',
    'addMachine.allCategories': 'all',
    'addMachine.searchLabel': 'search',
    'addMachine.searchPlaceholder': 'Type the machine name or alias',
    'addMachine.loading': 'Loading catalog...',
    'addMachine.emptyTitle': 'No machines found',
    'addMachine.emptyMessage':
        'Try another term or adjust the category filter.',
    'week.title': 'Your workouts',
    'week.todayBadge': 'TODAY',
    'week.emptyDay': 'No workout created yet.',
    'week.emptyHint':
        'Create a workout to organize chest, back, legs, or any split that makes sense to you.',
    'week.machineCount': '{count} machine{pluralSuffix}',
    'week.summary':
        '{workoutCount} saved workout{workoutSuffix} with {machineCount} machine{machineSuffix} in total.',
    'week.generated.title': 'Workout generated',
    'week.generated.message':
        'Your automatic workout was created successfully and replaced the current workouts.',
    'day.title': 'Workout',
    'day.machineCount': '{count} machine{pluralSuffix}',
    'day.addButton': 'Add machine',
    'day.maxWeight': 'max {weight}kg',
    'day.emptyDescription':
        'Adjust this workout however you want. Weekdays stay free for you to decide later.',
    'day.emptyMachines': 'No machine added yet.',
    'day.emptyMachinesHint':
        'Open the catalog and build the sequence for this workout with the machines you want.',
    'day.notFoundTitle': 'Workout not found',
    'day.notFoundMessage':
        'This workout may have been removed or has not been synced on this device yet.',
    'day.remove.title': 'Remove machine',
    'day.remove.message':
        'Remove "{name}" from this workout? History will be kept if it is still in another workout.',
    'day.removeWorkout.title': 'Remove workout',
    'day.removeWorkout.message':
        'Remove the workout "{name}"? Machines without history and without use in other workouts will also be cleaned up.',
    'workoutForm.createTitle': 'New workout',
    'workoutForm.editTitle': 'Edit workout',
    'workoutForm.nameLabel': 'title',
    'workoutForm.namePlaceholder': 'Ex.: back, chest, lower A',
    'workoutForm.descriptionLabel': 'description (optional)',
    'workoutForm.descriptionPlaceholder':
        'Describe the focus, notes, or strategy for this workout.',
    'workoutForm.createAction': 'Create workout',
    'workoutForm.saveAction': 'Save workout',
    'workoutForm.saving': 'Saving...',
    'workoutForm.nameRequired': 'Enter the workout title',
    'workoutForm.genericError': 'Unable to save the workout',
    'detail.permission.title': 'Permission required',
    'detail.permission.galleryMessage':
        'Allow gallery access to choose a photo for this machine.',
    'detail.permission.cameraMessage':
        'Allow camera access to take a photo of this machine.',
    'detail.photo.add': 'Add photo',
    'detail.photo.change': 'Change photo',
    'detail.photo.sourceMessage': 'Choose where the image should come from.',
    'detail.photo.useCamera': 'Use camera',
    'detail.photo.chooseGallery': 'Choose from gallery',
    'detail.photo.removeTitle': 'Remove photo?',
    'detail.photo.removeMessage':
        'The current image will be removed from this machine.',
    'detail.photo.removeAction': 'Remove photo',
    'detail.photo.actionsTitle': 'Machine photo',
    'detail.photo.actionsMessage': 'Choose what you want to do with the image.',
    'detail.record.title': 'record',
    'detail.record.subtitle':
        'Sequence with the highest saved volume for this machine.',
    'detail.record.empty': 'There is no saved record for this machine yet.',
    'detail.record.volume': 'volume {volume}',
    'detail.record.reps': '{value} reps',
    'detail.record.duration': '{value} duration',
    'detail.history.title': 'history',
    'detail.history.empty':
        'No records yet. Start a workout to save your progress.',
    'home.greetingFallback': 'athlete',
    'home.delta.noBase': 'No baseline',
    'home.delta.zero': '0',
    'home.relative.daysAgo': '{count} days',
    'home.featured.emptyTitle': 'progress by machine',
    'home.featured.emptySubtitle':
        'Set up your workouts to unlock this comparison for each exercise.',
    'home.featured.todayTitle': 'workout in focus',
    'home.featured.todaySubtitle':
        'Swipe sideways to see load progress for the machines in this workout.',
    'home.featured.nextTitle': 'workout in focus - {day}',
    'home.featured.nextSubtitle':
        'This is the next workout with enough machines to compare your progress.',
    'home.featured.focusCount': '{count} machine{pluralSuffix} in focus',
    'home.featured.noPlannedDays': 'No workout ready yet',
    'home.featured.emptyPanel':
        'Open your workouts, build the machines inside each split, and this area will start showing progress for each one.',
    'home.machine.comparison.noHistory':
        'There is no saved workout for this machine yet.',
    'home.machine.comparison.needMore':
        'Save one more workout to compare your progress.',
    'home.machine.comparison.default':
        'Current performance compared with the first saved record.',
    'home.machine.previous.noHistory': 'no history',
    'home.machine.previous.oneRecord': '1 saved record',
    'home.machine.previous.noComparison': 'no comparison',
    'home.machine.previous.vsLast': '{value} vs. last workout',
    'home.machine.lastTrained': 'last {label}',
    'home.machine.noTraining': 'no workout',
    'home.machine.metric.current': 'current',
    'home.machine.metric.initial': 'initial',
    'home.machine.metric.record': 'record',
    'home.machine.recordVolume': '{volume} volume',
    'home.machine.recordMetric': '{value} record',
    'home.machine.noHistoryCard':
        'This machine is already planned for the day, but it still has no saved history.',
    'home.machine.recordsTitle': 'latest records',
    'home.header.kicker': 'home dashboard',
    'home.header.greeting': 'Hi, {name}',
    'home.header.summaryWithHistory':
        'Current streak of {streak} day{streakSuffix} and {recent} active day{recentSuffix} in the last 7 days.',
    'home.header.summaryWithoutHistory':
        'You can already organize your workouts here, but the analysis gets much better after the first saved workout.',
    'home.header.lastWorkout': 'last workout',
    'home.header.nextTarget': 'next target',
    'home.header.noRecord': 'no record',
    'home.header.buildWeek': 'build your workouts',
    'home.header.openWeek': 'Open workouts',
    'home.stats.streakTitle': 'Streak',
    'home.stats.streakHint': 'days in a row{suffix}',
    'home.stats.streakHintZero': ' for now',
    'home.stats.last7Title': 'Last 7 days',
    'home.stats.last7Hint': 'days with saved workouts',
    'home.stats.monthTitle': 'This month',
    'home.stats.monthHint': 'days going to the gym',
    'home.stats.weekTitle': 'Workouts',
    'home.stats.weekHint': '{count} machine{pluralSuffix} distributed',
    'home.rhythm.kicker': 'workout library',
    'home.rhythm.titleWithCount': '{count} saved workout{daySuffix}',
    'home.rhythm.titleEmpty': 'You have not built any workout yet',
    'home.rhythm.subtitleWithNext': 'Next commitment: {next}.',
    'home.rhythm.subtitleEmpty':
        'Open your workout list to set up titles, machines, and categories you want to follow.',
    'home.nextPlanned.today': 'In focus - {count} machine{pluralSuffix}',
    'home.nextPlanned.tomorrow': 'Next - {count} machine{pluralSuffix}',
    'home.nextPlanned.other': '{day} - {count} machine{pluralSuffix}',
    'aiWizard.badge': 'workout with AI',
    'aiWizard.step.body': 'Your body data',
    'aiWizard.step.days': 'Which days will you train?',
    'aiWizard.step.preferences': 'Workout preferences',
    'aiWizard.step.intensity': 'What intensity?',
    'aiWizard.step.goal': 'What is your goal?',
    'aiWizard.step.instructions': 'Custom instructions',
    'aiWizard.step.review': 'Confirm generation',
    'aiWizard.actions.generate': 'Generate workout',
    'aiWizard.actions.generating': 'Generating...',
    'aiWizard.error.title': 'Error generating workout',
    'aiWizard.error.message': 'Unable to generate the workout right now.',
    'aiWizard.body.heightLabel': 'Height (cm)',
    'aiWizard.body.weightLabel': 'Weight (kg)',
    'aiWizard.body.hint': 'These values help calibrate the suggested loads.',
    'aiWizard.days.description':
        'Mark the exact days you want to go to the gym. AI will use that to build a more precise split.',
    'aiWizard.days.empty': 'Select at least one day.',
    'aiWizard.days.selectedCount':
        '{count} day{daySuffix} selected{selectedSuffix}.',
    'aiWizard.preferences.description':
        'These fields are optional. Fill them in if you want AI to respect a time cap, daily volume, or a specific split model.',
    'aiWizard.preferences.minutesLabel': 'Minutes per day',
    'aiWizard.preferences.minutesPlaceholder': 'Ex.: 45, 60, or 90',
    'aiWizard.preferences.machinesLabel': 'Machines per day',
    'aiWizard.preferences.machinesPlaceholder': 'Ex.: 6',
    'aiWizard.preferences.splitLabel': 'Split model',
    'aiWizard.preferences.splitPlaceholder': 'Ex.: ABC, ABCAB, fullbody',
    'aiWizard.intensity.light.title': 'light',
    'aiWizard.intensity.light.description': 'Beginner or returning',
    'aiWizard.intensity.moderate.title': 'moderate',
    'aiWizard.intensity.moderate.description': 'Consistent training',
    'aiWizard.intensity.intense.title': 'intense',
    'aiWizard.intensity.intense.description': 'High volume and load',
    'aiWizard.goal.hypertrophy.title': 'hypertrophy',
    'aiWizard.goal.hypertrophy.description': 'Muscle gain',
    'aiWizard.goal.strength.title': 'strength',
    'aiWizard.goal.strength.description': 'Higher max load',
    'aiWizard.goal.endurance.title': 'endurance',
    'aiWizard.goal.endurance.description': 'More reps and stamina',
    'aiWizard.goal.weightLoss.title': 'weight loss',
    'aiWizard.goal.weightLoss.description': 'Fat loss with training',
    'aiWizard.instructions.description':
        'Add notes for the AI, such as injuries, exercises you want to avoid, focus on a muscle group, or equipment available at your gym.',
    'aiWizard.instructions.placeholder':
        'Ex.: avoid free squats because of knee pain and prioritize machines.',
    'aiWizard.review.title': 'generation summary',
    'aiWizard.review.height': 'Height',
    'aiWizard.review.weight': 'Weight',
    'aiWizard.review.selectedDays': 'Selected days',
    'aiWizard.review.totalDays': 'Total days',
    'aiWizard.review.hoursPerDay': 'Minutes per day',
    'aiWizard.review.machinesPerDay': 'Machines per day',
    'aiWizard.review.split': 'Split model',
    'aiWizard.review.intensity': 'Intensity',
    'aiWizard.review.goal': 'Goal',
    'aiWizard.review.instructions': 'Custom instructions',
    'aiWizard.review.notInformed': 'Not informed',
    'aiWizard.review.noSpecificSplit': 'No specific split',
    'aiWizard.review.noAdditionalNotes': 'No additional notes.',
    'aiWizard.review.promptNote':
        'The final prompt is now assembled only in the backend before calling the AI.',
    'workout.saved.title': 'Workout finished!',
    'workout.saved.message':
        '{count} machine{machineSuffix} recorded{registeredSuffix} in {elapsed}',
    'workout.empty.title': 'Empty workout',
    'workout.empty.message': 'No exercise was recorded.',
    'workout.error.title': 'Save error',
    'workout.error.message':
        'Unable to save the workout right now. Please try again shortly.',
    'workout.incomplete.title': 'No complete exercise',
    'workout.incomplete.message':
        'There is still no exercise ready to save. If you leave now, your drafts will be discarded.',
    'workout.incomplete.confirm': 'Leave without saving',
    'workout.pending.title': 'Finish with pending items?',
    'workout.pending.message':
        'Some machines still needs review. You can save now or keep reviewing.',
    'workout.quit.title': 'Quit workout?',
    'workout.quit.message':
        'If you leave now, the workout will end and nothing will be saved.',
    'workout.quit.confirm': 'Quit',
    'workout.series.one': 'Set 1',
    'workout.series.two': 'Set 2',
    'workout.series.three': 'Set 3',
    'workout.position': '{current} of {total}',
    'workout.completedProgress': '{completed}/{total} complete',
    'workout.swapHint':
        'Use the arrows or tap the cards to switch machines without losing your drafts.',
    'workout.status.registeredTitle': 'Exercise logged',
    'workout.status.draftTitle': 'Draft saved',
    'workout.status.skipTitle': 'You can skip without breaking the flow',
    'workout.status.registeredMessage':
        'You can move on now or come back later to review this exercise.',
    'workout.status.draftMessage':
        'Values stay saved when switching machines. Finish it when the machine is free.',
    'workout.status.skipMessage':
        'If the machine is busy, move on now and come back whenever you want using the cards above.',
    'workout.rest.title': 'rest',
    'workout.rest.idle':
        'The timer starts as soon as you confirm a set or finish a timed exercise.',
    'workout.rest.active': 'Counting since the last confirmed set.',
    'workout.duration.title': 'timed log',
    'workout.duration.idle':
        'Tap to start and count how long you stay on this exercise.',
    'workout.duration.active':
        'The timer is running. Finish when you are done with the exercise.',
    'workout.duration.done':
        'Time recorded. Tap to restart if you want to do it again.',
    'workout.duration.startCta': 'Start',
    'workout.duration.stopCta': 'Finish',
    'workout.duration.restartCta': 'Restart',
    'workout.duration.lastRecord': 'Last {value}',
    'workout.fillSeries': 'fill in the exercise sets',
    'workout.series.confirmCta': 'Confirm',
    'workout.series.confirmedCta': 'Confirmed',
    'workout.series.readyState': 'Ready',
    'workout.series.lockedState': 'Locked',
    'workout.series.confirmedState': 'Confirmed',
    'workout.series.lockedHint':
        'Confirm the previous set to unlock the next one.',
    'workout.series.weightLabel': 'Weight',
    'workout.series.repsLabel': 'Reps',
    'workout.resume.title': 'Workout in progress',
    'workout.resume.message':
        'We found a workout in progress saved on this device. You can resume where you left off or discard this draft.',
    'workout.resume.confirm': 'Resume workout',
    'workout.resume.cancel': 'Discard',
    'workout.nextMachine': 'Next machine',
    'services.aiWorkout.generateError':
        'Unable to generate the workout automatically',
    'services.workouts.loadError': 'Unable to load the workouts',
    'services.workouts.createError': 'Unable to create the workout',
    'services.workouts.updateError': 'Unable to update the workout',
    'services.workouts.deleteError': 'Unable to remove the workout',
    'services.workouts.addMachineError':
        'Unable to add the machine to the workout',
    'services.workouts.removeMachineError':
        'Unable to remove the machine from the workout',
    'services.machines.loadError': 'Unable to load the machines',
    'services.machines.updateError': 'Unable to update the machine',
    'services.history.loadError': 'Unable to load the history',
    'services.history.saveError': 'Unable to save the workout',
    'services.credit.loadError': 'Unable to load your credits',
    'services.credit.checkoutError': 'Unable to generate the Pix',
    'services.axios.missingApiUrl': 'Set EXPO_PUBLIC_API_URL in frontend/.env',
    'notifications.emulatorUnsupported':
        'Notifications do not work on the emulator',
    'notifications.channelName': 'Workout reminders',
    'notifications.message1.title': "Let's train! 💪",
    'notifications.message1.body':
        "Today is {categories} day. Don't leave it for tomorrow!",
    'notifications.message2.title': 'Gym time! 🏋️',
    'notifications.message2.body':
        'Your {categories} workout is waiting for you.',
    'notifications.message3.title': "It's time! ⚡",
    'notifications.message3.body': '{categories} day. Time to load the bar!',
    'notifications.message4.title': 'Workout of the day 🔥',
    'notifications.message4.body':
        "{categories} is on today's menu. See you at the gym!",
    'notifications.message5.title': "Don't skip your workout! 💪",
    'notifications.message5.body':
        'Today you have {categories}. Your body will thank you.',
}
