import type { TranslationDictionary } from "./index";

export const esES: TranslationDictionary = {
    "app.tagline": "Tu ficha de entrenamiento digital",
    "common.or": "o",
    "common.actions.back": "Volver",
    "common.actions.close": "Cerrar",
    "common.actions.enter": "Entrar",
    "common.actions.createAccount": "Crear cuenta",
    "common.actions.understand": "Entendido",
    "auth.login.emailLabel": "Correo",
    "auth.login.emailPlaceholder": "tu@email.com",
    "auth.login.passwordLabel": "Contraseña",
    "auth.login.passwordPlaceholder": "********",
    "auth.login.submit": "Entrar",
    "auth.login.submitting": "Entrando...",
    "auth.login.createAccountCta": "Crear cuenta",
    "auth.register.title": "Crear cuenta",
    "auth.register.subtitle": "Completa tus datos para empezar",
    "auth.register.nameLabel": "Nombre",
    "auth.register.namePlaceholder": "Tu nombre",
    "auth.register.emailLabel": "Correo",
    "auth.register.emailPlaceholder": "tu@email.com",
    "auth.register.passwordLabel": "Contraseña",
    "auth.register.passwordPlaceholder": "Mínimo 6 caracteres",
    "auth.register.confirmPasswordLabel": "Confirmar contraseña",
    "auth.register.confirmPasswordPlaceholder": "Repite la contraseña",
    "auth.register.submit": "Crear cuenta",
    "auth.register.submitting": "Creando cuenta...",
    "auth.register.hasAccountPrefix": "¿Ya tienes cuenta?",
    "auth.validation.nameRequired": "Ingresa tu nombre",
    "auth.validation.emailRequired": "Ingresa tu correo",
    "auth.validation.emailInvalid": "Correo inválido",
    "auth.validation.passwordRequired": "Ingresa tu contraseña",
    "auth.validation.passwordCreateRequired": "Ingresa una contraseña",
    "auth.validation.passwordMin": "Mínimo de 6 caracteres",
    "auth.validation.confirmPasswordRequired": "Confirma tu contraseña",
    "auth.validation.passwordMismatch": "Las contraseñas no coinciden",
    "auth.errors.invalidCredentials": "Correo o contraseña incorrectos",
    "auth.errors.emailAlreadyExists": "Este correo ya está en uso",
    "auth.errors.genericLogin": "No fue posible iniciar sesión",
    "auth.errors.genericRegister": "No fue posible crear la cuenta",
    "auth.errors.serviceUnavailableTitle": "Servicio no disponible",
    "auth.errors.serviceUnavailableMessage":
        "El servicio puede no estar disponible en este momento. Inténtalo de nuevo en unos instantes.",
    "navigation.profile": "Perfil",
    "profile.kicker": "perfil",
    "profile.header.description":
        "Ajusta tu nombre, correo y contraseña localmente y acompaña la suscripción que libera el modo AI.",
    "profile.language.title": "Idioma de la app",
    "profile.language.description":
        "Elige el idioma predeterminado guardado en este dispositivo. Las pantallas ya migradas cambian al instante.",
    "profile.ai.subtitle": "Plan mensual con pago por Pix",
    "profile.ai.status.active": "Activo",
    "profile.ai.status.inactive": "Inactivo",
    "profile.ai.description":
        "El acceso a AI se habilita automáticamente cuando se aprueba el pago por Pix y permanece activo durante 1 mes.",
    "profile.ai.benefit.assistantButton":
        "Libera el botón del asistente de entrenamiento con IA en la pantalla inicial.",
    "profile.ai.benefit.autoActivation":
        "Activación automática en cuanto Mercado Pago confirme el Pix.",
    "profile.ai.benefit.accessWindow":
        "Acceso garantizado por 1 mes sin cancelación manual durante la vigencia.",
    "profile.ai.activeTitle": "Plan activo",
    "profile.ai.activeDescriptionWithDate":
        "Válido hasta {date}. Durante este período no hay opción de cancelación manual.",
    "profile.ai.activeDescription": "Tu acceso a AI ya fue liberado en la app.",
    "profile.ai.pendingTitle": "Pago pendiente",
    "profile.ai.pendingDescriptionWithDate":
        "Hay un Pix esperando pago hasta {date}.",
    "profile.ai.pendingDescription":
        "Hay un Pix esperando pago para activar el modo AI.",
    "profile.ai.continuePayment": "Continuar pago",
    "profile.ai.subscribe": "Suscribirse al plan AI",
    "profile.form.title": "Tus datos",
    "profile.form.description": "Estos cambios todavía se guardan solo localmente en el frontend.",
    "profile.form.newPasswordLabel": "Nueva contraseña",
    "profile.form.newPasswordPlaceholder": "Cambia solo si quieres",
    "profile.form.confirmNewPasswordLabel": "Confirmar nueva contraseña",
    "profile.form.confirmNewPasswordPlaceholder": "Repite la nueva contraseña",
    "profile.form.save": "Guardar cambios",
    "profile.form.saving": "Guardando...",
    "profile.form.saveError": "No fue posible guardar el perfil",
    "profile.alert.savedTitle": "Perfil guardado",
    "profile.alert.savedMessage": "Los cambios quedaron guardados solo en este frontend.",
    "planCheckout.title": "Suscribirse a Fitcha AI",
    "planCheckout.description":
        "Al pagar este Pix, los beneficios del plan quedan activos por 1 mes. Durante este período el modo AI sigue habilitado sin opción de cancelación manual.",
    "planCheckout.whatYouGet": "Lo que recibes",
    "planCheckout.benefit.aiAccess":
        "Acceso al asistente de entrenamiento con IA por 1 mes después de la aprobación del pago.",
    "planCheckout.benefit.autoActivation":
        "Activación automática cuando Mercado Pago confirme el Pix.",
    "planCheckout.benefit.renewal":
        "Nueva suscripción solo después de que termine el período actual.",
    "planCheckout.documentLabel": "CPF del pagador",
    "planCheckout.documentPlaceholder": "00000000000",
    "planCheckout.generatePix": "Generar Pix",
    "planCheckout.generatingPix": "Generando Pix...",
    "planCheckout.planFallback": "Plan Fitcha AI",
    "planCheckout.status.paid": "Pagado",
    "planCheckout.status.awaitingPix": "Esperando Pix",
    "planCheckout.status.pending": "Pendiente",
    "planCheckout.pixValidUntil": "Pix válido hasta {date}.",
    "planCheckout.planActiveUntil": "Plan activo hasta {date}.",
    "planCheckout.copyPastePix": "Pix copia y pega",
    "planCheckout.approvedMessage":
        "Pago confirmado. El botón de IA ya debería aparecer en las pantallas donde la función está disponible.",
    "planCheckout.checkPayment": "Verificar pago",
    "planCheckout.openCharge": "Abrir cobro",
    "planCheckout.error.loadPlan": "No fue posible cargar el plan",
    "planCheckout.error.invalidCpf": "Ingresa un CPF válido con 11 dígitos",
    "planCheckout.error.generatePix": "No fue posible generar el Pix",
};
