import type { TranslationDictionary } from "./index";

export const esES: TranslationDictionary = {
    "app.tagline": "Tu ficha de entrenamiento digital",
    "common.or": "o",
    "common.actions.back": "Volver",
    "common.actions.close": "Cerrar",
    "common.actions.continue": "Continuar",
    "common.actions.enter": "Entrar",
    "common.actions.createAccount": "Crear cuenta",
    "common.actions.understand": "Entendido",
    "common.actions.cancel": "Cancelar",
    "common.actions.confirm": "Confirmar",
    "common.actions.add": "Agregar",
    "common.actions.next": "Siguiente",
    "common.actions.finish": "Finalizar",
    "common.actions.finishWorkout": "Finalizar entrenamiento",
    "common.actions.remove": "Eliminar",
    "common.actions.startWorkout": "Iniciar entrenamiento",
    "common.units.cm": "cm",
    "common.units.kg": "kg",
    "common.relative.today": "hoy",
    "common.relative.yesterday": "ayer",
    "common.relative.daysAgo": "hace {count} dias",
    "common.relative.weekAgo": "1 semana",
    "common.relative.weeksAgo": "{count} semanas",
    "common.days.sunday": "Domingo",
    "common.days.monday": "Lunes",
    "common.days.tuesday": "Martes",
    "common.days.wednesday": "Miercoles",
    "common.days.thursday": "Jueves",
    "common.days.friday": "Viernes",
    "common.days.saturday": "Sabado",
    "common.daysShort.sunday": "Dom",
    "common.daysShort.monday": "Lun",
    "common.daysShort.tuesday": "Mar",
    "common.daysShort.wednesday": "Mie",
    "common.daysShort.thursday": "Jue",
    "common.daysShort.friday": "Vie",
    "common.daysShort.saturday": "Sab",
    "auth.login.emailLabel": "Correo",
    "auth.login.emailPlaceholder": "tu@email.com",
    "auth.login.passwordLabel": "Contrasena",
    "auth.login.passwordPlaceholder": "********",
    "auth.login.submit": "Entrar",
    "auth.login.submitting": "Entrando...",
    "auth.login.forgotPasswordCta": "Olvide mi contrasena",
    "auth.login.createAccountCta": "Crear cuenta",
    "auth.register.title": "Crear cuenta",
    "auth.register.subtitle": "Completa tus datos para empezar",
    "auth.register.nameLabel": "Nombre",
    "auth.register.namePlaceholder": "Tu nombre",
    "auth.register.emailLabel": "Correo",
    "auth.register.emailPlaceholder": "tu@email.com",
    "auth.register.passwordLabel": "Contrasena",
    "auth.register.passwordPlaceholder": "Minimo 6 caracteres",
    "auth.register.confirmPasswordLabel": "Confirmar contrasena",
    "auth.register.confirmPasswordPlaceholder": "Repite la contrasena",
    "auth.register.submit": "Crear cuenta",
    "auth.register.submitting": "Creando cuenta...",
    "auth.register.hasAccountPrefix": "Ya tienes cuenta?",
    "auth.validation.nameRequired": "Ingresa tu nombre",
    "auth.validation.emailRequired": "Ingresa tu correo",
    "auth.validation.emailInvalid": "Correo invalido",
    "auth.validation.passwordRequired": "Ingresa tu contrasena",
    "auth.validation.passwordCreateRequired": "Ingresa una contrasena",
    "auth.validation.passwordMin": "Minimo de 6 caracteres",
    "auth.validation.confirmPasswordRequired": "Confirma tu contrasena",
    "auth.validation.passwordMismatch": "Las contrasenas no coinciden",
    "auth.errors.invalidCredentials": "Correo o contrasena incorrectos",
    "auth.errors.emailAlreadyExists": "Este correo ya esta en uso",
    "auth.errors.emailNotVerified": "Verifica tu correo antes de entrar",
    "auth.errors.genericLogin": "No fue posible iniciar sesion",
    "auth.errors.genericRegister": "No fue posible crear la cuenta",
    "auth.errors.serviceUnavailableTitle": "Servicio no disponible",
    "auth.errors.serviceUnavailableMessage":
        "El servicio puede no estar disponible en este momento. Intentalo de nuevo en unos instantes.",
    "auth.sessionExpired.title": "Sesion expirada",
    "auth.sessionExpired.message":
        "Tu acceso expiro mientras la app estaba cerrada. Inicia sesion otra vez para continuar.",
    "auth.resetPassword.title": "Recuperar acceso",
    "auth.resetPassword.description":
        "Ingresa tu correo y enviaremos un enlace para restablecer tu contrasena.",
    "auth.resetPassword.submit": "Enviar enlace",
    "auth.resetPassword.submitting": "Enviando...",
    "auth.resetPassword.successTitle": "Revisa tu correo",
    "auth.resetPassword.successMessage":
        "Si existe una cuenta para {email}, enviaremos un enlace para restablecer tu contrasena.",
    "auth.resetPassword.error": "No fue posible enviar el enlace de restablecimiento",
    "auth.register.successTitle": "Revisa tu correo",
    "auth.register.successMessage":
        "Tu cuenta fue creada. Enviamos un enlace de verificacion a {email}. Despues de eso, vuelve a la app para entrar.",
    "navigation.profile": "Perfil",
    "navigation.machineDetail": "Detalle",
    "profile.kicker": "perfil",
    "profile.header.description":
        "Ajusta tu nombre, correo y contrasena localmente y acompana tu saldo de creditos para generar entrenamientos con IA.",
    "profile.language.title": "Idioma de la app",
    "profile.language.description":
        "Elige el idioma predeterminado guardado en este dispositivo. Las pantallas ya migradas cambian al instante.",
    "profile.credits.title": "Creditos Fitcha AI",
    "profile.credits.subtitle": "1 credito = 1 entrenamiento personalizado",
    "profile.credits.description":
        "Compra creditos individuales por Pix. El saldo se libera automaticamente apenas el pago sea aprobado.",
    "profile.credits.balanceLabel": "Creditos disponibles",
    "profile.credits.balanceHint": "Cada generacion completada consume 1 credito.",
    "profile.credits.pendingTitle": "Pago pendiente",
    "profile.credits.pendingDescriptionWithDate":
        "Hay un Pix de {quantity} credito(s) esperando pago hasta {date}.",
    "profile.credits.pendingDescription": "Hay un Pix esperando pago para liberar mas creditos.",
    "profile.credits.continuePayment": "Continuar pago",
    "profile.credits.buy": "Comprar creditos",
    "profile.form.title": "Tus datos",
    "profile.form.description": "Estos cambios todavia se guardan solo localmente en el frontend.",
    "profile.form.newPasswordLabel": "Nueva contrasena",
    "profile.form.newPasswordPlaceholder": "Cambia solo si quieres",
    "profile.form.confirmNewPasswordLabel": "Confirmar nueva contrasena",
    "profile.form.confirmNewPasswordPlaceholder": "Repite la nueva contrasena",
    "profile.form.save": "Guardar cambios",
    "profile.form.saving": "Guardando...",
    "profile.form.saveError": "No fue posible guardar el perfil",
    "profile.alert.savedTitle": "Perfil guardado",
    "profile.alert.savedMessage": "Los cambios quedaron guardados solo en este frontend.",
    "creditCheckout.title": "Comprar creditos",
    "creditCheckout.description":
        "Paga con Pix y recibe creditos para generar entrenamientos personalizados con IA en Fitcha.",
    "creditCheckout.step.quantity": "Cantidad",
    "creditCheckout.step.document": "CPF",
    "creditCheckout.step.payment": "Pix",
    "creditCheckout.quantityTitle": "Cuantos creditos quieres comprar?",
    "creditCheckout.quantityDescription":
        "Cada credito libera 1 nueva generacion de entrenamiento con IA.",
    "creditCheckout.quantityLabel": "Cantidad de creditos",
    "creditCheckout.quantityPlaceholder": "1",
    "creditCheckout.quantityHint": "Cada credito cuesta {price}. Total estimado: {total}.",
    "creditCheckout.documentTitle": "Ingresa el CPF del pagador",
    "creditCheckout.documentDescription":
        "Usamos el CPF solo para generar el cobro Pix en Mercado Pago.",
    "creditCheckout.documentLabel": "CPF del pagador",
    "creditCheckout.documentPlaceholder": "00000000000",
    "creditCheckout.generatePix": "Generar Pix",
    "creditCheckout.generatingPix": "Generando Pix...",
    "creditCheckout.paymentFallback": "Compra de creditos Fitcha AI",
    "creditCheckout.summaryCredits": "{count} credito(s)",
    "creditCheckout.status.paid": "Pagado",
    "creditCheckout.status.awaitingPix": "Esperando Pix",
    "creditCheckout.status.pending": "Pendiente",
    "creditCheckout.pixValidUntil": "Pix valido hasta {date}.",
    "creditCheckout.copyPastePix": "Pix copia y pega",
    "creditCheckout.approvedMessage":
        "Pago confirmado. Tus creditos ya estan disponibles en la app.",
    "creditCheckout.checkPayment": "Verificar pago",
    "creditCheckout.openCharge": "Abrir cobro",
    "creditCheckout.error.loadSummary": "No fue posible cargar tus creditos",
    "creditCheckout.error.invalidQuantity": "Ingresa una cantidad valida de creditos",
    "creditCheckout.error.invalidCpf": "Ingresa un CPF valido con 11 digitos",
    "creditCheckout.error.generatePix": "No fue posible generar el Pix",
    "aiWizard.noCredits.title": "No tienes creditos",
    "aiWizard.noCredits.description":
        "Cada entrenamiento generado con IA consume 1 credito. Compra creditos para continuar.",
    "aiWizard.noCredits.buy": "Comprar creditos",
    "categories.peito": "Pecho",
    "categories.costas": "Espalda",
    "categories.pernas": "Piernas",
    "categories.ombros": "Hombros",
    "categories.biceps": "Biceps",
    "categories.triceps": "Triceps",
    "categories.core": "Core",
    "categories.cardio": "Cardio",
    "addMachine.title": "Nueva maquina",
    "addMachine.nameLabel": "nombre",
    "addMachine.namePlaceholder": "Ej.: press de banca",
    "addMachine.descriptionLabel": "descripcion (opcional)",
    "addMachine.descriptionPlaceholder": "Detalles sobre el ejercicio...",
    "addMachine.categoryLabel": "categoria",
    "addMachine.allCategories": "todas",
    "addMachine.searchLabel": "buscar",
    "addMachine.searchPlaceholder": "Escribe el nombre o alias de la maquina",
    "addMachine.loading": "Cargando catalogo...",
    "addMachine.emptyTitle": "No se encontraron maquinas",
    "addMachine.emptyMessage": "Prueba otro termino o ajusta el filtro de categoria.",
    "week.title": "Tu semana",
    "week.todayBadge": "HOY",
    "week.emptyDay": "Todavia no hay maquinas planificadas.",
    "week.machineCount": "{count} maquina{pluralSuffix}",
    "week.generated.title": "Entrenamiento generado",
    "week.generated.message":
        "Tu entrenamiento automatico fue creado con exito y reemplazo la semana actual.",
    "day.machineCount": "{count} maquina{pluralSuffix}",
    "day.addButton": "Agregar maquina",
    "day.maxWeight": "max {weight}kg",
    "day.remove.title": "Eliminar maquina",
    "day.remove.message":
        'Eliminar "{name}" de este dia? El historial se mantendra si sigue en otro dia.',
    "detail.permission.title": "Permiso necesario",
    "detail.permission.galleryMessage":
        "Permite acceso a la galeria para elegir una foto de la maquina.",
    "detail.permission.cameraMessage":
        "Permite acceso a la camara para registrar una foto de la maquina.",
    "detail.photo.add": "Agregar foto",
    "detail.photo.change": "Cambiar foto",
    "detail.photo.sourceMessage": "Elige de donde debe venir la imagen.",
    "detail.photo.useCamera": "Usar camara",
    "detail.photo.chooseGallery": "Elegir de la galeria",
    "detail.photo.removeTitle": "Eliminar foto?",
    "detail.photo.removeMessage": "La imagen actual sera eliminada de esta maquina.",
    "detail.photo.removeAction": "Eliminar foto",
    "detail.photo.actionsTitle": "Foto de la maquina",
    "detail.photo.actionsMessage": "Elige lo que quieres hacer con la imagen.",
    "detail.record.title": "record",
    "detail.record.subtitle":
        "Secuencia de 3 series con el mayor volumen guardado en esta maquina.",
    "detail.record.empty": "Todavia no hay un record guardado para esta maquina.",
    "detail.record.volume": "volumen {volume}kg",
    "detail.history.title": "historial",
    "detail.history.empty": "Todavia no hay registros. Inicia un entrenamiento para guardar pesos.",
    "home.greetingFallback": "atleta",
    "home.delta.noBase": "Sin base",
    "home.delta.zero": "0 kg",
    "home.relative.daysAgo": "{count} dias",
    "home.featured.emptyTitle": "evolucion por maquina",
    "home.featured.emptySubtitle":
        "Organiza tu semana para desbloquear esta comparacion por ejercicio.",
    "home.featured.todayTitle": "maquinas de hoy",
    "home.featured.todaySubtitle":
        "Desliza al lado para ver la evolucion de carga en cada maquina.",
    "home.featured.nextTitle": "proximo entrenamiento - {day}",
    "home.featured.nextSubtitle":
        "Hoy no hay maquinas planificadas, asi que la comparacion usa el siguiente dia activo.",
    "home.featured.focusCount": "{count} maquina{pluralSuffix} en foco",
    "home.featured.noPlannedDays": "Todavia no hay dias planificados",
    "home.featured.emptyPanel":
        "Abre Week, distribuye las maquinas en los dias de la semana y esta area empezara a mostrar la evolucion de cada una.",
    "home.machine.comparison.noHistory":
        "Todavia no existe un entrenamiento guardado para esta maquina.",
    "home.machine.comparison.needMore": "Guarda un entrenamiento mas para comparar tu evolucion.",
    "home.machine.comparison.default":
        "Comparacion de la carga actual contra el primer registro guardado.",
    "home.machine.previous.noHistory": "sin historial",
    "home.machine.previous.oneRecord": "1 registro guardado",
    "home.machine.previous.noComparison": "sin comparacion",
    "home.machine.previous.vsLast": "{value} vs. ultimo entrenamiento",
    "home.machine.lastTrained": "ultimo {label}",
    "home.machine.noTraining": "sin entrenamiento",
    "home.machine.metric.current": "actual",
    "home.machine.metric.initial": "inicial",
    "home.machine.metric.record": "record",
    "home.machine.recordVolume": "{volume} de volumen",
    "home.machine.noHistoryCard":
        "Esta maquina ya esta en el dia planificado, pero todavia no tiene historial guardado.",
    "home.machine.recordsTitle": "ultimos registros",
    "home.header.kicker": "panel inicial",
    "home.header.greeting": "Hola, {name}",
    "home.header.summaryWithHistory":
        "Racha actual de {streak} dia{streakSuffix} y {recent} dia{recentSuffix} activo{activeSuffix} en los ultimos 7 dias.",
    "home.header.summaryWithoutHistory":
        "Ya puedes organizar tu semana aqui, pero el analisis mejora mucho despues del primer entrenamiento guardado.",
    "home.header.lastWorkout": "ultimo entrenamiento",
    "home.header.nextTarget": "proximo objetivo",
    "home.header.noRecord": "sin registro",
    "home.header.buildWeek": "arma tu semana",
    "home.header.openWeek": "Abrir semana",
    "home.stats.streakTitle": "Racha",
    "home.stats.streakHint": "dias seguidos{suffix}",
    "home.stats.streakHintZero": " por ahora",
    "home.stats.last7Title": "Ultimos 7 dias",
    "home.stats.last7Hint": "dias con entrenamiento guardado",
    "home.stats.monthTitle": "En el mes",
    "home.stats.monthHint": "dias yendo al gimnasio",
    "home.stats.weekTitle": "Semana",
    "home.stats.weekHint": "{count} maquina{pluralSuffix} planificada{pluralSuffix}",
    "home.rhythm.kicker": "ritmo de la semana",
    "home.rhythm.titleWithCount": "{count} dia{daySuffix} ya armado{builtSuffix}",
    "home.rhythm.titleEmpty": "Tu semana todavia esta vacia",
    "home.rhythm.subtitleWithNext": "Proximo compromiso: {next}.",
    "home.rhythm.subtitleEmpty":
        "Abre Week para armar los dias, maquinas y categorias que quieres seguir.",
    "home.nextPlanned.today": "Hoy - {count} maquina{pluralSuffix}",
    "home.nextPlanned.tomorrow": "Manana - {count} maquina{pluralSuffix}",
    "home.nextPlanned.other": "{day} - {count} maquina{pluralSuffix}",
    "aiWizard.badge": "entrenamiento con IA",
    "aiWizard.step.body": "Tus datos fisicos",
    "aiWizard.step.days": "Que dias vas a entrenar?",
    "aiWizard.step.preferences": "Preferencias del entrenamiento",
    "aiWizard.step.intensity": "Que intensidad?",
    "aiWizard.step.goal": "Cual es tu objetivo?",
    "aiWizard.step.instructions": "Instrucciones personalizadas",
    "aiWizard.step.review": "Confirmar generacion",
    "aiWizard.actions.generate": "Generar entrenamiento",
    "aiWizard.actions.generating": "Generando...",
    "aiWizard.error.title": "Error al generar el entrenamiento",
    "aiWizard.error.message": "No fue posible generar el entrenamiento ahora.",
    "aiWizard.body.heightLabel": "Altura (cm)",
    "aiWizard.body.weightLabel": "Peso (kg)",
    "aiWizard.body.hint": "Estos datos ayudan a calibrar las cargas sugeridas.",
    "aiWizard.days.description":
        "Marca exactamente los dias en que quieres ir al gimnasio. La IA usara eso para montar una division mas precisa.",
    "aiWizard.days.empty": "Selecciona al menos un dia.",
    "aiWizard.days.selectedCount": "{count} dia{daySuffix} seleccionado{selectedSuffix}.",
    "aiWizard.preferences.description":
        "Estos campos son opcionales. Completalos si quieres que la IA respete un limite de tiempo, volumen diario o un modelo de division especifico.",
    "aiWizard.preferences.hoursLabel": "Horas por dia",
    "aiWizard.preferences.hoursPlaceholder": "Ej.: 1, 1.5 o 2",
    "aiWizard.preferences.machinesLabel": "Maquinas por dia",
    "aiWizard.preferences.machinesPlaceholder": "Ej.: 6",
    "aiWizard.preferences.splitLabel": "Modelo de division",
    "aiWizard.preferences.splitPlaceholder": "Ej.: ABC, ABCAB, fullbody",
    "aiWizard.intensity.light.title": "leve",
    "aiWizard.intensity.light.description": "Principiante o regreso",
    "aiWizard.intensity.moderate.title": "moderada",
    "aiWizard.intensity.moderate.description": "Entrenamiento consistente",
    "aiWizard.intensity.intense.title": "intensa",
    "aiWizard.intensity.intense.description": "Alto volumen y carga",
    "aiWizard.goal.hypertrophy.title": "hipertrofia",
    "aiWizard.goal.hypertrophy.description": "Ganancia de masa muscular",
    "aiWizard.goal.strength.title": "fuerza",
    "aiWizard.goal.strength.description": "Aumento de carga maxima",
    "aiWizard.goal.endurance.title": "resistencia",
    "aiWizard.goal.endurance.description": "Mas repeticiones y stamina",
    "aiWizard.goal.weightLoss.title": "adelgazamiento",
    "aiWizard.goal.weightLoss.description": "Perdida de grasa con entrenamiento",
    "aiWizard.instructions.description":
        "Agrega observaciones para la IA, como lesiones, ejercicios que prefieres evitar, foco en algun grupo muscular o equipos disponibles en tu gimnasio.",
    "aiWizard.instructions.placeholder":
        "Ej.: evitar sentadilla libre por dolor de rodilla y priorizar maquinas.",
    "aiWizard.review.title": "resumen de la generacion",
    "aiWizard.review.height": "Altura",
    "aiWizard.review.weight": "Peso",
    "aiWizard.review.selectedDays": "Dias elegidos",
    "aiWizard.review.totalDays": "Total de dias",
    "aiWizard.review.hoursPerDay": "Horas por dia",
    "aiWizard.review.machinesPerDay": "Maquinas por dia",
    "aiWizard.review.split": "Modelo de division",
    "aiWizard.review.intensity": "Intensidad",
    "aiWizard.review.goal": "Objetivo",
    "aiWizard.review.instructions": "Instrucciones personalizadas",
    "aiWizard.review.notInformed": "No informado",
    "aiWizard.review.noSpecificSplit": "Ningun modelo especifico",
    "aiWizard.review.noAdditionalNotes": "Ninguna observacion adicional.",
    "aiWizard.review.promptNote":
        "El prompt final ahora se arma solo en el backend antes de llamar a la IA.",
    "workout.saved.title": "Entrenamiento finalizado!",
    "workout.saved.message":
        "{count} maquina{machineSuffix} registrada{registeredSuffix} en {elapsed}",
    "workout.empty.title": "Entrenamiento vacio",
    "workout.empty.message": "No se registro ningun peso.",
    "workout.error.title": "Error al guardar",
    "workout.error.message":
        "No fue posible guardar el entrenamiento ahora. Intentalo de nuevo en unos instantes.",
    "workout.incomplete.title": "Ninguna maquina completa",
    "workout.incomplete.message":
        "Todavia no hay ejercicio con las 3 series completas. Si sales ahora, los borradores se descartaran.",
    "workout.incomplete.confirm": "Salir sin guardar",
    "workout.pending.title": "Finalizar con pendientes?",
    "workout.pending.message":
        "{count} maquina{machineSuffix} sin las 3 series completas. Puedes guardar ahora o seguir revisando.",
    "workout.quit.title": "Cerrar entrenamiento?",
    "workout.quit.message": "Si sales ahora, el entrenamiento terminara y no se guardara nada.",
    "workout.quit.confirm": "Cerrar",
    "workout.series.one": "Serie 1",
    "workout.series.two": "Serie 2",
    "workout.series.three": "Serie 3",
    "workout.position": "{current} de {total}",
    "workout.completedProgress": "{completed}/{total} completas",
    "workout.swapHint":
        "Usa las flechas o toca las tarjetas para cambiar de maquina sin perder los borradores.",
    "workout.status.registeredTitle": "Ejercicio registrado",
    "workout.status.draftTitle": "Borrador guardado",
    "workout.status.skipTitle": "Puedes saltarlo sin romper el flujo",
    "workout.status.registeredMessage":
        "Puedes seguir ahora o volver despues para ajustar los pesos.",
    "workout.status.draftMessage":
        "Los valores quedan guardados al cambiar de maquina. Completa cuando quede libre.",
    "workout.status.skipMessage":
        "Si la maquina esta ocupada, avanza ahora y vuelve cuando quieras usando las tarjetas de arriba.",
    "workout.rest.title": "descanso",
    "workout.rest.idle": "El timer empieza apenas confirmas una serie.",
    "workout.rest.active": "Contando desde la ultima serie confirmada.",
    "workout.fillSeries": "completa y confirma las 3 series",
    "workout.series.confirmCta": "Confirmar",
    "workout.series.confirmedCta": "Confirmada",
    "workout.series.readyState": "Lista",
    "workout.series.lockedState": "Bloqueada",
    "workout.series.confirmedState": "Confirmada",
    "workout.series.lockedHint": "Confirma la serie anterior para desbloquear la siguiente.",
    "workout.nextMachine": "Siguiente maquina",
    "services.aiWorkout.generateError": "No fue posible generar el entrenamiento automaticamente",
    "services.days.loadError": "No fue posible cargar los dias",
    "services.days.addError": "No fue posible agregar la maquina",
    "services.days.removeError": "No fue posible eliminar la maquina",
    "services.days.replaceError": "No fue posible reemplazar la semana",
    "services.machines.loadError": "No fue posible cargar las maquinas",
    "services.machines.updateError": "No fue posible actualizar la maquina",
    "services.history.loadError": "No fue posible cargar el historial",
    "services.history.saveError": "No fue posible guardar el entrenamiento",
    "services.credit.loadError": "No fue posible cargar tus creditos",
    "services.credit.checkoutError": "No fue posible generar el Pix",
    "services.axios.missingApiUrl": "Configura EXPO_PUBLIC_API_URL en frontend/.env",
    "notifications.emulatorUnsupported": "Las notificaciones no funcionan en el emulador",
    "notifications.channelName": "Recordatorios de entrenamiento",
    "notifications.message1.title": "Vamos a entrenar! 💪",
    "notifications.message1.body": "Hoy toca {categories}. No lo dejes para manana!",
    "notifications.message2.title": "Hora del hierro! 🏋️",
    "notifications.message2.body": "Tu entrenamiento de {categories} te esta esperando.",
    "notifications.message3.title": "Es la hora! ⚡",
    "notifications.message3.body": "Dia de {categories}. Vamos a meter carga!",
    "notifications.message4.title": "Entrenamiento del dia 🔥",
    "notifications.message4.body": "{categories} en el menu de hoy. Ven al gimnasio!",
    "notifications.message5.title": "No faltes al entrenamiento! 💪",
    "notifications.message5.body": "Hoy hay {categories}. Tu cuerpo te lo va a agradecer.",
};
