export const ptBR = {
    "app.tagline": "Sua ficha de treino digital",
    "common.or": "ou",
    "common.actions.back": "Voltar",
    "common.actions.close": "Fechar",
    "common.actions.continue": "Continuar",
    "common.actions.enter": "Entrar",
    "common.actions.createAccount": "Criar conta",
    "common.actions.understand": "Entendi",
    "auth.login.emailLabel": "E-mail",
    "auth.login.emailPlaceholder": "seu@email.com",
    "auth.login.passwordLabel": "Senha",
    "auth.login.passwordPlaceholder": "********",
    "auth.login.submit": "Entrar",
    "auth.login.submitting": "Entrando...",
    "auth.login.createAccountCta": "Criar conta",
    "auth.register.title": "Criar conta",
    "auth.register.subtitle": "Preencha seus dados para começar",
    "auth.register.nameLabel": "Nome",
    "auth.register.namePlaceholder": "Seu nome",
    "auth.register.emailLabel": "E-mail",
    "auth.register.emailPlaceholder": "seu@email.com",
    "auth.register.passwordLabel": "Senha",
    "auth.register.passwordPlaceholder": "Mínimo 6 caracteres",
    "auth.register.confirmPasswordLabel": "Confirmar senha",
    "auth.register.confirmPasswordPlaceholder": "Repita a senha",
    "auth.register.submit": "Criar conta",
    "auth.register.submitting": "Criando conta...",
    "auth.register.hasAccountPrefix": "Já tem conta?",
    "auth.validation.nameRequired": "Informe seu nome",
    "auth.validation.emailRequired": "Informe seu e-mail",
    "auth.validation.emailInvalid": "E-mail inválido",
    "auth.validation.passwordRequired": "Informe sua senha",
    "auth.validation.passwordCreateRequired": "Informe uma senha",
    "auth.validation.passwordMin": "Mínimo de 6 caracteres",
    "auth.validation.confirmPasswordRequired": "Confirme sua senha",
    "auth.validation.passwordMismatch": "As senhas não coincidem",
    "auth.errors.invalidCredentials": "E-mail ou senha incorretos",
    "auth.errors.emailAlreadyExists": "Este e-mail já está em uso",
    "auth.errors.genericLogin": "Não foi possível entrar",
    "auth.errors.genericRegister": "Não foi possível criar a conta",
    "auth.errors.serviceUnavailableTitle": "Serviço indisponível",
    "auth.errors.serviceUnavailableMessage":
        "O serviço pode estar indisponível no momento. Tente novamente em instantes.",
    "navigation.profile": "Perfil",
    "profile.kicker": "perfil",
    "profile.header.description":
        "Ajuste seu nome, e-mail e senha localmente e acompanhe seu saldo de créditos para gerar treinos com IA.",
    "profile.language.title": "Idioma do app",
    "profile.language.description":
        "Escolha o idioma padrão salvo neste dispositivo. As telas já migradas mudam na hora.",
    "profile.credits.title": "Créditos Fitcha AI",
    "profile.credits.subtitle": "1 crédito = 1 treino customizado",
    "profile.credits.description":
        "Compre créditos avulsos via Pix. O saldo é liberado automaticamente assim que o pagamento for aprovado.",
    "profile.credits.balanceLabel": "Créditos disponíveis",
    "profile.credits.balanceHint": "Cada geração concluída consome 1 crédito.",
    "profile.credits.pendingTitle": "Pagamento pendente",
    "profile.credits.pendingDescriptionWithDate":
        "Existe um Pix de {quantity} crédito(s) aguardando pagamento até {date}.",
    "profile.credits.pendingDescription":
        "Existe um Pix aguardando pagamento para liberar mais créditos.",
    "profile.credits.continuePayment": "Continuar pagamento",
    "profile.credits.buy": "Comprar créditos",
    "profile.form.title": "Seus dados",
    "profile.form.description": "Essas alterações continuam locais no frontend por enquanto.",
    "profile.form.newPasswordLabel": "Nova senha",
    "profile.form.newPasswordPlaceholder": "Mude apenas se quiser",
    "profile.form.confirmNewPasswordLabel": "Confirmar nova senha",
    "profile.form.confirmNewPasswordPlaceholder": "Repita a nova senha",
    "profile.form.save": "Salvar alterações",
    "profile.form.saving": "Salvando...",
    "profile.form.saveError": "Não foi possível salvar o perfil",
    "profile.alert.savedTitle": "Perfil salvo",
    "profile.alert.savedMessage": "As alterações ficaram armazenadas apenas neste frontend.",
    "creditCheckout.title": "Comprar créditos",
    "creditCheckout.description":
        "Pague via Pix e receba créditos para gerar treinos customizados com IA no Fitcha.",
    "creditCheckout.step.quantity": "Quantidade",
    "creditCheckout.step.document": "CPF",
    "creditCheckout.step.payment": "Pix",
    "creditCheckout.quantityTitle": "Quantos créditos você quer comprar?",
    "creditCheckout.quantityDescription":
        "Cada crédito libera 1 nova geração de treino com IA.",
    "creditCheckout.quantityLabel": "Quantidade de créditos",
    "creditCheckout.quantityPlaceholder": "1",
    "creditCheckout.quantityHint": "Cada crédito custa {price}. Total estimado: {total}.",
    "creditCheckout.documentTitle": "Informe o CPF do pagador",
    "creditCheckout.documentDescription":
        "Usamos o CPF apenas para gerar a cobrança Pix no Mercado Pago.",
    "creditCheckout.documentLabel": "CPF do pagador",
    "creditCheckout.documentPlaceholder": "00000000000",
    "creditCheckout.generatePix": "Gerar Pix",
    "creditCheckout.generatingPix": "Gerando Pix...",
    "creditCheckout.paymentFallback": "Compra de créditos Fitcha AI",
    "creditCheckout.summaryCredits": "{count} crédito(s)",
    "creditCheckout.status.paid": "Pago",
    "creditCheckout.status.awaitingPix": "Aguardando Pix",
    "creditCheckout.status.pending": "Pendente",
    "creditCheckout.pixValidUntil": "Pix válido até {date}.",
    "creditCheckout.copyPastePix": "Pix cópia e cola",
    "creditCheckout.approvedMessage":
        "Pagamento confirmado. Seus créditos já estão disponíveis no app.",
    "creditCheckout.checkPayment": "Verificar pagamento",
    "creditCheckout.openCharge": "Abrir cobrança",
    "creditCheckout.error.loadSummary": "Não foi possível carregar seus créditos",
    "creditCheckout.error.invalidQuantity": "Informe uma quantidade válida de créditos",
    "creditCheckout.error.invalidCpf": "Informe um CPF válido com 11 dígitos",
    "creditCheckout.error.generatePix": "Não foi possível gerar o Pix",
    "aiWizard.noCredits.title": "Você está sem créditos",
    "aiWizard.noCredits.description":
        "Cada treino gerado com IA consome 1 crédito. Compre créditos para continuar.",
    "aiWizard.noCredits.buy": "Comprar créditos",
} as const;
