export const ptBR = {
    'app.tagline': 'Sua ficha de treino digital',
    'appUpdate.title': 'Nova versão disponível',
    'appUpdate.message':
        'A versão {latestVersion} do Fitcha já está disponível. Você está usando a versão {currentVersion}.',
    'appUpdate.requiredMessage':
        'Existe uma atualização obrigatória disponível para continuar usando o app. Versão atual: {currentVersion}. Nova versão: {latestVersion}.',
    'appUpdate.confirm': 'Baixar agora',
    'appUpdate.cancel': 'Depois',
    'appUpdate.otaTitle': 'Atualização disponível',
    'appUpdate.otaMessage':
        'Existe uma atualização interna pronta para aplicar. O app será reiniciado após sua confirmação.',
    'appUpdate.otaConfirm': 'Atualizar agora',
    'appUpdate.otaApplying': 'Atualizando...',
    'appUpdate.errorTitle': 'Erro ao atualizar',
    'appUpdate.otaErrorMessage':
        'Não foi possível aplicar a atualização agora. Tente novamente em instantes.',
    'common.or': 'ou',
    'common.actions.back': 'Voltar',
    'common.actions.close': 'Fechar',
    'common.actions.continue': 'Continuar',
    'common.actions.enter': 'Entrar',
    'common.actions.createAccount': 'Criar conta',
    'common.actions.understand': 'Entendi',
    'common.actions.cancel': 'Cancelar',
    'common.actions.confirm': 'Confirmar',
    'common.actions.add': 'Adicionar',
    'common.actions.next': 'Próximo',
    'common.actions.finish': 'Finalizar',
    'common.actions.finishWorkout': 'Finalizar treino',
    'common.actions.remove': 'Remover',
    'common.actions.startWorkout': 'Iniciar treino',
    'common.units.cm': 'cm',
    'common.units.kg': 'kg',
    'common.relative.today': 'hoje',
    'common.relative.yesterday': 'ontem',
    'common.relative.daysAgo': '{count} dias atrás',
    'common.relative.weekAgo': '1 semana',
    'common.relative.weeksAgo': '{count} semanas',
    'common.days.sunday': 'Domingo',
    'common.days.monday': 'Segunda',
    'common.days.tuesday': 'Terça',
    'common.days.wednesday': 'Quarta',
    'common.days.thursday': 'Quinta',
    'common.days.friday': 'Sexta',
    'common.days.saturday': 'Sábado',
    'common.daysShort.sunday': 'Dom',
    'common.daysShort.monday': 'Seg',
    'common.daysShort.tuesday': 'Ter',
    'common.daysShort.wednesday': 'Qua',
    'common.daysShort.thursday': 'Qui',
    'common.daysShort.friday': 'Sex',
    'common.daysShort.saturday': 'Sáb',
    'auth.login.emailLabel': 'E-mail',
    'auth.login.emailPlaceholder': 'seu@email.com',
    'auth.login.passwordLabel': 'Senha',
    'auth.login.passwordPlaceholder': '********',
    'auth.login.submit': 'Entrar',
    'auth.login.submitting': 'Entrando...',
    'auth.login.forgotPasswordCta': 'Esqueci minha senha',
    'auth.login.createAccountCta': 'Criar conta',
    'auth.register.title': 'Criar conta',
    'auth.register.subtitle': 'Preencha seus dados para começar',
    'auth.register.nameLabel': 'Nome',
    'auth.register.namePlaceholder': 'Seu nome',
    'auth.register.emailLabel': 'E-mail',
    'auth.register.emailPlaceholder': 'seu@email.com',
    'auth.register.passwordLabel': 'Senha',
    'auth.register.passwordPlaceholder': 'Mínimo 6 caracteres',
    'auth.register.confirmPasswordLabel': 'Confirmar senha',
    'auth.register.confirmPasswordPlaceholder': 'Repita a senha',
    'auth.register.submit': 'Criar conta',
    'auth.register.submitting': 'Criando conta...',
    'auth.register.hasAccountPrefix': 'Já tem conta?',
    'auth.validation.nameRequired': 'Informe seu nome',
    'auth.validation.emailRequired': 'Informe seu e-mail',
    'auth.validation.emailInvalid': 'E-mail inválido',
    'auth.validation.passwordRequired': 'Informe sua senha',
    'auth.validation.passwordCreateRequired': 'Informe uma senha',
    'auth.validation.passwordMin': 'Mínimo de 6 caracteres',
    'auth.validation.confirmPasswordRequired': 'Confirme sua senha',
    'auth.validation.passwordMismatch': 'As senhas não coincidem',
    'auth.errors.invalidCredentials': 'E-mail ou senha incorretos',
    'auth.errors.emailAlreadyExists': 'Este e-mail já está em uso',
    'auth.errors.emailNotVerified': 'Verifique seu e-mail antes de entrar',
    'auth.errors.currentPasswordInvalid': 'A senha atual está incorreta',
    'auth.errors.genericLogin': 'Não foi possível entrar',
    'auth.errors.genericRegister': 'Não foi possível criar a conta',
    'auth.errors.serviceUnavailableTitle': 'Serviço indisponível',
    'auth.errors.serviceUnavailableMessage':
        'O serviço pode estar indisponível no momento. Tente novamente em instantes.',
    'auth.sessionExpired.title': 'Sessão expirada',
    'auth.sessionExpired.message':
        'Seu acesso expirou enquanto o app estava fechado. Entre novamente para continuar.',
    'auth.resetPassword.title': 'Recuperar acesso',
    'auth.resetPassword.description':
        'Informe seu e-mail e enviaremos um link para redefinir sua senha.',
    'auth.resetPassword.submit': 'Enviar link',
    'auth.resetPassword.submitting': 'Enviando...',
    'auth.resetPassword.successTitle': 'Verifique seu e-mail',
    'auth.resetPassword.successMessage':
        'Se existir uma conta para {email}, enviaremos um link para redefinir sua senha.',
    'auth.resetPassword.error': 'Não foi possível enviar o link de redefinição',
    'auth.register.successTitle': 'Verifique seu e-mail',
    'auth.register.successMessage':
        'Sua conta foi criada. Enviamos um link de verificação para {email}. Depois disso, volte ao app para entrar.',
    'navigation.profile': 'Perfil',
    'navigation.machineDetail': 'Detalhe',
    'profile.kicker': 'perfil',
    'profile.header.description':
        'Consulte os dados da conta autenticada e gerencie seu saldo de créditos para gerar treinos com IA.',
    'profile.language.title': 'Idioma do app',
    'profile.theme.title': 'Aparência',
    'profile.theme.description': 'Escolha como o app deve ser exibido.',
    'profile.theme.dark': 'Tema escuro',
    'profile.theme.light': 'Tema claro',
    'profile.logout': 'Sair da conta',
    'profile.language.description':
        'Escolha o idioma padrão salvo neste dispositivo. As telas já migradas mudam na hora.',
    'profile.credits.title': 'Créditos Fitcha AI',
    'profile.credits.subtitle': '1 crédito = 1 treino customizado',
    'profile.credits.description':
        'Compre créditos avulsos via Pix. O saldo é liberado automaticamente assim que o pagamento for aprovado.',
    'profile.credits.balanceLabel': 'Créditos disponíveis',
    'profile.credits.balanceHint': 'Cada geração concluída consome 1 crédito.',
    'profile.credits.pendingTitle': 'Pagamento pendente',
    'profile.credits.pendingDescriptionWithDate':
        'Existe um Pix de {quantity} crédito(s) aguardando pagamento até {date}.',
    'profile.credits.pendingDescription':
        'Existe um Pix aguardando pagamento para liberar mais créditos.',
    'profile.credits.continuePayment': 'Continuar pagamento',
    'profile.credits.buy': 'Comprar créditos',
    'profile.form.title': 'Segurança',
    'profile.form.description': 'Altere a senha real da sua conta.',
    'profile.form.currentPasswordLabel': 'Senha atual',
    'profile.form.currentPasswordPlaceholder': 'Digite sua senha atual',
    'profile.form.currentPasswordRequired': 'Informe sua senha atual',
    'profile.form.newPasswordRequired': 'Informe uma nova senha',
    'profile.form.newPasswordLabel': 'Nova senha',
    'profile.form.newPasswordPlaceholder': 'Mínimo 6 caracteres',
    'profile.form.confirmNewPasswordLabel': 'Confirmar nova senha',
    'profile.form.confirmNewPasswordPlaceholder': 'Repita a nova senha',
    'profile.form.save': 'Atualizar senha',
    'profile.form.saving': 'Salvando...',
    'profile.form.saveError': 'Não foi possível atualizar a senha',
    'profile.alert.savedTitle': 'Senha atualizada',
    'profile.alert.savedMessage': 'Sua senha foi atualizada com sucesso.',
    'creditCheckout.title': 'Comprar créditos',
    'creditCheckout.description':
        'Pague via Pix e receba créditos para gerar treinos customizados com IA no Fitcha.',
    'creditCheckout.step.quantity': 'Quantidade',
    'creditCheckout.step.document': 'CPF',
    'creditCheckout.step.payment': 'Pix',
    'creditCheckout.quantityTitle': 'Quantos créditos você quer comprar?',
    'creditCheckout.quantityDescription':
        'Cada crédito libera 1 nova geração de treino com IA.',
    'creditCheckout.quantityLabel': 'Quantidade de créditos',
    'creditCheckout.quantityPlaceholder': '1',
    'creditCheckout.quantityHint':
        'Cada crédito custa {price}. Total estimado: {total}.',
    'creditCheckout.documentTitle': 'Informe o CPF do pagador',
    'creditCheckout.documentDescription':
        'Usamos o CPF apenas para gerar a cobrança Pix no Mercado Pago.',
    'creditCheckout.documentLabel': 'CPF do pagador',
    'creditCheckout.documentPlaceholder': '00000000000',
    'creditCheckout.generatePix': 'Gerar Pix',
    'creditCheckout.generatingPix': 'Gerando Pix...',
    'creditCheckout.paymentFallback': 'Compra de créditos Fitcha AI',
    'creditCheckout.summaryCredits': '{count} crédito(s)',
    'creditCheckout.status.paid': 'Pago',
    'creditCheckout.status.awaitingPix': 'Aguardando Pix',
    'creditCheckout.status.pending': 'Pendente',
    'creditCheckout.pixValidUntil': 'Pix válido até {date}.',
    'creditCheckout.copyPastePix': 'Pix cópia e cola',
    'creditCheckout.approvedMessage':
        'Pagamento confirmado. Seus créditos já estão disponíveis no app.',
    'creditCheckout.checkPayment': 'Verificar pagamento',
    'creditCheckout.openCharge': 'Abrir cobrança',
    'creditCheckout.error.loadSummary':
        'Não foi possível carregar seus créditos',
    'creditCheckout.error.invalidQuantity':
        'Informe uma quantidade válida de créditos',
    'creditCheckout.error.invalidCpf': 'Informe um CPF válido com 11 dígitos',
    'creditCheckout.error.generatePix': 'Não foi possível gerar o Pix',
    'aiWizard.noCredits.title': 'Você está sem créditos',
    'aiWizard.noCredits.description':
        'Cada treino gerado com IA consome 1 crédito. Compre créditos para continuar.',
    'aiWizard.noCredits.buy': 'Comprar créditos',
    'categories.peito': 'Peito',
    'categories.costas': 'Costas',
    'categories.pernas': 'Pernas',
    'categories.ombros': 'Ombros',
    'categories.biceps': 'Bíceps',
    'categories.triceps': 'Tríceps',
    'categories.antebraco': 'Antebraço',
    'categories.core': 'Core',
    'categories.cardio': 'Cardio',
    'addMachine.title': 'Nova máquina',
    'addMachine.nameLabel': 'nome',
    'addMachine.namePlaceholder': 'Ex.: supino reto',
    'addMachine.descriptionLabel': 'descrição (opcional)',
    'addMachine.descriptionPlaceholder': 'Detalhes sobre o exercício...',
    'addMachine.categoryLabel': 'categoria',
    'addMachine.allCategories': 'todas',
    'addMachine.searchLabel': 'buscar',
    'addMachine.searchPlaceholder': 'Digite o nome ou apelido da máquina',
    'addMachine.loading': 'Carregando catálogo...',
    'addMachine.emptyTitle': 'Nenhuma máquina encontrada',
    'addMachine.emptyMessage':
        'Tente outro nome ou ajuste o filtro de categoria.',
    'week.title': 'Seus treinos',
    'week.todayBadge': 'HOJE',
    'week.emptyDay': 'Nenhum treino criado ainda.',
    'week.emptyHint':
        'Crie um treino para organizar peito, costas, pernas ou qualquer divisão que fizer sentido para você.',
    'week.machineCount': '{count} máquina{pluralSuffix}',
    'week.summary':
        '{workoutCount} treino{workoutSuffix} salvo{workoutSuffix} com {machineCount} máquina{machineSuffix} no total.',
    'week.aiAction': 'Montar treino com IA',
    'week.aiDescription':
        'Responda algumas perguntas e receba uma divisao pronta.',
    'week.generated.title': 'Treino gerado',
    'week.generated.message':
        'Seu treino automático foi criado com sucesso e substituiu os treinos atuais.',
    'day.title': 'Treino',
    'day.machineCount': '{count} máquina{pluralSuffix}',
    'day.addButton': 'Adicionar máquina',
    'day.maxWeight': 'máx. {weight}kg',
    'day.emptyDescription':
        'Ajuste este treino como quiser. Os dias da semana ficam livres para você decidir depois.',
    'day.emptyMachines': 'Nenhuma máquina adicionada ainda.',
    'day.emptyMachinesHint':
        'Abra o catálogo e monte a sequência deste treino com as máquinas que quiser.',
    'day.notFoundTitle': 'Treino não encontrado',
    'day.notFoundMessage':
        'Esse treino pode ter sido removido ou ainda não foi sincronizado neste dispositivo.',
    'day.remove.title': 'Remover máquina',
    'day.remove.message':
        'Remover "{name}" deste treino? O histórico será mantido se ela continuar em outro treino.',
    'day.removeWorkout.title': 'Remover treino',
    'day.removeWorkout.message':
        'Remover o treino "{name}"? As máquinas sem histórico e sem uso em outros treinos também serão limpas.',
    'workoutForm.createTitle': 'Novo treino',
    'workoutForm.editTitle': 'Editar treino',
    'workoutForm.nameLabel': 'título',
    'workoutForm.namePlaceholder': 'Ex.: costas, peito, inferior A',
    'workoutForm.descriptionLabel': 'descrição (opcional)',
    'workoutForm.descriptionPlaceholder':
        'Descreva foco, observações ou estratégia desse treino.',
    'workoutForm.createAction': 'Criar treino',
    'workoutForm.saveAction': 'Salvar treino',
    'workoutForm.saving': 'Salvando...',
    'workoutForm.nameRequired': 'Informe o título do treino',
    'workoutForm.genericError': 'Não foi possível salvar o treino',
    'detail.permission.title': 'Permissão necessária',
    'detail.permission.galleryMessage':
        'Permita acesso à galeria para selecionar uma foto da máquina.',
    'detail.permission.cameraMessage':
        'Permita acesso à câmera para registrar uma foto da máquina.',
    'detail.photo.add': 'Adicionar foto',
    'detail.photo.change': 'Trocar foto',
    'detail.photo.sourceMessage': 'Escolha de onde a imagem deve vir.',
    'detail.photo.useCamera': 'Usar câmera',
    'detail.photo.chooseGallery': 'Escolher da galeria',
    'detail.photo.removeTitle': 'Remover foto?',
    'detail.photo.removeMessage': 'A imagem atual será removida desta máquina.',
    'detail.photo.removeAction': 'Remover foto',
    'detail.photo.actionsTitle': 'Foto da máquina',
    'detail.photo.actionsMessage': 'Escolha o que deseja fazer com a imagem.',
    'detail.record.title': 'recorde',
    'detail.record.subtitle':
        'Sequência com maior volume já salva nessa máquina.',
    'detail.record.empty': 'Ainda não há recorde salvo para essa máquina.',
    'detail.record.volume': 'volume {volume}',
    'detail.record.reps': '{value} reps',
    'detail.record.duration': '{value} de duração',
    'detail.progress.title': 'evolução',
    'detail.progress.subtitle': 'Linha com o progresso salvo nessa máquina.',
    'detail.progress.empty':
        'Ainda não há histórico suficiente para desenhar o gráfico.',
    'detail.progress.metric.weight': 'volume',
    'detail.progress.metric.reps': 'reps',
    'detail.progress.metric.duration': 'duração',
    'detail.history.title': 'histórico',
    'detail.history.empty':
        'Nenhum registro ainda. Inicie um treino para salvar sua evolução.',
    'detail.history.holdHint': 'Segure um registro para iniciar a exclusão.',
    'detail.history.deleteAccessibilityLabel':
        'Excluir registro de treino de {date}',
    'detail.history.deleteTitle': 'Excluir registro?',
    'detail.history.deleteMessage':
        'O registro de {date} será removido permanentemente.',
    'detail.history.deleteConfirm': 'Excluir registro',
    'detail.history.deleteErrorTitle': 'Não foi possível excluir',
    'detail.transfer.headerAccessibilityLabel':
        'Transferir todo o histórico para outra máquina',
    'detail.transfer.title': 'Transferir histórico',
    'detail.transfer.subtitle':
        'Escolha a máquina que receberá todo o histórico de {name}.',
    'detail.transfer.loadError':
        'Não foi possível carregar as máquinas disponíveis.',
    'detail.transfer.empty':
        'Nenhuma máquina compatível foi encontrada para essa transferência.',
    'detail.transfer.mineBadge': 'minha máquina',
    'detail.transfer.catalogBadge': 'catálogo',
    'detail.transfer.scopeTitle': 'Substituir também nos treinos?',
    'detail.transfer.scopeMessage':
        'O histórico de {source} será transferido para {target}. Escolha se a máquina também deve ser substituída nos treinos em que aparece.',
    'detail.transfer.historyAndWorkouts': 'Histórico e treinos',
    'detail.transfer.historyOnly': 'Somente histórico',
    'home.greetingFallback': 'atleta',
    'home.delta.noBase': 'Sem base',
    'home.delta.zero': '0',
    'home.relative.daysAgo': '{count} dias',
    'home.featured.emptyTitle': 'evolução por máquina',
    'home.featured.emptySubtitle':
        'Monte seus treinos para destravar essa comparação por exercício.',
    'home.featured.todayTitle': 'treino em foco',
    'home.featured.todaySubtitle':
        'Arraste para o lado e veja a evolução de carga nas máquinas desse treino.',
    'home.featured.nextTitle': 'treino em foco - {day}',
    'home.featured.nextSubtitle':
        'Esse treino é o próximo com máquinas suficientes para comparação de evolução.',
    'home.featured.focusCount': '{count} máquina{pluralSuffix} em foco',
    'home.featured.noPlannedDays': 'Nenhum treino pronto ainda',
    'home.featured.emptyPanel':
        'Abra a lista de treinos, monte as máquinas de cada divisão e esta área passa a mostrar a evolução de cada uma.',
    'home.machine.comparison.noHistory':
        'Ainda não existe treino salvo nessa máquina.',
    'home.machine.comparison.needMore':
        'Salve mais um treino para comparar a evolução.',
    'home.machine.comparison.default':
        'Comparação do desempenho (volume total) atual contra o primeiro registro salvo.',
    'home.machine.previous.noHistory': 'sem histórico',
    'home.machine.previous.oneRecord': '1 registro salvo',
    'home.machine.previous.noComparison': 'sem comparação',
    'home.machine.previous.vsLast': '{value} vs. último treino',
    'home.machine.lastTrained': 'último {label}',
    'home.machine.noTraining': 'sem treino',
    'home.machine.metric.current': 'atual',
    'home.machine.metric.initial': 'inicial',
    'home.machine.metric.record': 'recorde',
    'home.machine.recordVolume': '{volume} de volume',
    'home.machine.recordMetric': '{value} no recorde',
    'home.machine.noHistoryCard':
        'Essa máquina já está no dia planejado, mas ainda não tem histórico salvo.',
    'home.machine.recordsTitle': 'últimos registros',
    'home.header.kicker': 'painel inicial',
    'home.header.greeting': 'Olá, {name}',
    'home.header.summaryWithHistory':
        'Sequência atual de {streak} dia{streakSuffix} e {recent} dia{recentSuffix} ativo{activeSuffix} nos últimos 7 dias.',
    'home.header.summaryWithoutHistory':
        'Seus treinos já podem ser organizados aqui, mas a análise fica muito melhor depois do primeiro treino salvo.',
    'home.header.lastWorkout': 'último treino',
    'home.header.nextTarget': 'próximo alvo',
    'home.header.noRecord': 'sem registro',
    'home.header.buildWeek': 'monte seus treinos',
    'home.header.openWeek': 'Abrir treinos',
    'home.stats.streakTitle': 'Sequência',
    'home.stats.streakHint': 'dias seguidos{suffix}',
    'home.stats.streakHintZero': ' por enquanto',
    'home.stats.last7Title': 'Últimos 7 dias',
    'home.stats.last7Hint': 'dias com treino salvo',
    'home.stats.monthTitle': 'No mês',
    'home.stats.monthHint': 'dias indo para a academia',
    'home.stats.weekTitle': 'Treinos',
    'home.stats.weekHint':
        '{count} máquina{pluralSuffix} distribuída{pluralSuffix}',
    'home.rhythm.kicker': 'biblioteca de treinos',
    'home.rhythm.titleWithCount':
        '{count} treino{daySuffix} salvo{builtSuffix}',
    'home.rhythm.titleEmpty': 'Você ainda não montou nenhum treino',
    'home.rhythm.subtitleWithNext': 'Próximo compromisso: {next}.',
    'home.rhythm.subtitleEmpty':
        'Abra a lista de treinos para montar títulos, máquinas e categorias que quer seguir.',
    'home.nextPlanned.today': 'Em foco - {count} máquina{pluralSuffix}',
    'home.nextPlanned.tomorrow': 'Próximo - {count} máquina{pluralSuffix}',
    'home.nextPlanned.other': '{day} - {count} máquina{pluralSuffix}',
    'aiWizard.badge': 'treino com IA',
    'aiWizard.step.body': 'Seus dados físicos',
    'aiWizard.step.days': 'Quais dias você vai treinar?',
    'aiWizard.step.preferences': 'Preferências do treino',
    'aiWizard.step.intensity': 'Qual a intensidade?',
    'aiWizard.step.goal': 'Qual é o seu objetivo?',
    'aiWizard.step.instructions': 'Instruções personalizadas',
    'aiWizard.step.review': 'Confirmar geração',
    'aiWizard.actions.generate': 'Gerar treino',
    'aiWizard.actions.generating': 'Gerando...',
    'aiWizard.error.title': 'Erro ao gerar treino',
    'aiWizard.error.message': 'Não foi possível gerar o treino agora.',
    'aiWizard.body.heightLabel': 'Altura (cm)',
    'aiWizard.body.weightLabel': 'Peso (kg)',
    'aiWizard.body.hint': 'Esses dados ajudam a calibrar os pesos sugeridos.',
    'aiWizard.days.description':
        'Marque exatamente os dias em que você quer ir para a academia. A IA vai usar isso para montar a divisão com mais precisão.',
    'aiWizard.days.empty': 'Selecione pelo menos um dia.',
    'aiWizard.days.selectedCount':
        '{count} dia{daySuffix} selecionado{selectedSuffix}.',
    'aiWizard.preferences.description':
        'Esses campos são opcionais. Preencha se quiser que a IA respeite um limite de tempo, volume diário ou um modelo de divisão específico.',
    'aiWizard.preferences.minutesLabel': 'Minutos por dia',
    'aiWizard.preferences.minutesPlaceholder': 'Ex.: 45, 60 ou 90',
    'aiWizard.preferences.machinesLabel': 'Máquinas por dia',
    'aiWizard.preferences.machinesPlaceholder': 'Ex.: 6',
    'aiWizard.preferences.splitLabel': 'Modelo de divisão',
    'aiWizard.preferences.splitPlaceholder': 'Ex.: ABC, ABCAB, fullbody',
    'aiWizard.intensity.light.title': 'leve',
    'aiWizard.intensity.light.description': 'Iniciante ou retorno',
    'aiWizard.intensity.moderate.title': 'moderado',
    'aiWizard.intensity.moderate.description': 'Treino consistente',
    'aiWizard.intensity.intense.title': 'intenso',
    'aiWizard.intensity.intense.description': 'Alto volume e carga',
    'aiWizard.goal.hypertrophy.title': 'hipertrofia',
    'aiWizard.goal.hypertrophy.description': 'Ganho de massa muscular',
    'aiWizard.goal.strength.title': 'força',
    'aiWizard.goal.strength.description': 'Aumento de carga máxima',
    'aiWizard.goal.endurance.title': 'resistência',
    'aiWizard.goal.endurance.description': 'Mais repetições e stamina',
    'aiWizard.goal.weightLoss.title': 'emagrecimento',
    'aiWizard.goal.weightLoss.description': 'Perda de gordura com treino',
    'aiWizard.instructions.description':
        'Adicione observações para a IA, como lesões, exercícios que você prefere evitar, foco em algum grupo muscular ou equipamentos que a academia tem.',
    'aiWizard.instructions.placeholder':
        'Ex.: evitar agachamento livre por dor no joelho e priorizar máquinas.',
    'aiWizard.review.title': 'resumo da geração',
    'aiWizard.review.height': 'Altura',
    'aiWizard.review.weight': 'Peso',
    'aiWizard.review.selectedDays': 'Dias escolhidos',
    'aiWizard.review.totalDays': 'Total de dias',
    'aiWizard.review.hoursPerDay': 'Minutos por dia',
    'aiWizard.review.machinesPerDay': 'Máquinas por dia',
    'aiWizard.review.split': 'Modelo de divisão',
    'aiWizard.review.intensity': 'Intensidade',
    'aiWizard.review.goal': 'Objetivo',
    'aiWizard.review.instructions': 'Instruções personalizadas',
    'aiWizard.review.notInformed': 'Não informado',
    'aiWizard.review.noSpecificSplit': 'Nenhum modelo específico',
    'aiWizard.review.noAdditionalNotes': 'Nenhuma observação adicional.',
    'aiWizard.review.promptNote':
        'O prompt final agora é montado somente no backend antes de chamar a IA.',
    'workout.saved.title': 'Treino finalizado!',
    'workout.saved.message':
        '{count} máquina{machineSuffix} registrada{registeredSuffix} em {elapsed}',
    'workout.empty.title': 'Treino vazio',
    'workout.empty.message': 'Nenhum exercício foi registrado.',
    'workout.error.title': 'Erro ao salvar',
    'workout.error.message':
        'Não foi possível salvar o treino agora. Tente novamente em instantes.',
    'workout.incomplete.title': 'Nenhum exercício completo',
    'workout.incomplete.message':
        'Ainda não há exercício pronto para salvar. Se sair agora, os rascunhos serão descartados.',
    'workout.incomplete.confirm': 'Sair sem salvar',
    'workout.pending.title': 'Finalizar com pendências?',
    'workout.pending.message':
        'Algumas máquinas ainda precisam de revisão. Você pode salvar agora ou continuar revisando.',
    'workout.quit.title': 'Encerrar treino?',
    'workout.quit.message':
        'Se você sair agora, o treino será encerrado e nada será salvo.',
    'workout.quit.confirm': 'Encerrar',
    'workout.series.one': 'Série 1',
    'workout.series.two': 'Série 2',
    'workout.series.three': 'Série 3',
    'workout.position': '{current} de {total}',
    'workout.completedProgress': '{completed}/{total} completas',
    'workout.rest.title': 'descanso',
    'workout.rest.idle':
        'O timer começa assim que você confirmar uma série ou finalizar um exercício por tempo.',
    'workout.rest.active': 'Contando desde a última série confirmada.',
    'workout.duration.title': 'registro por tempo',
    'workout.duration.idle':
        'Toque para iniciar e contar quanto tempo você fica nesse exercício.',
    'workout.duration.active':
        'O cronômetro está rodando. Finalize quando encerrar o exercício.',
    'workout.duration.done':
        'Tempo registrado. Toque para reiniciar se quiser refazer.',
    'workout.duration.startCta': 'Iniciar',
    'workout.duration.stopCta': 'Finalizar',
    'workout.duration.restartCta': 'Reiniciar',
    'workout.duration.lastRecord': 'Último {value}',
    'workout.fillSeries': 'preencha as séries do exercício',
    'workout.series.confirmCta': 'Confirmar',
    'workout.series.confirmedCta': 'Confirmada',
    'workout.series.readyState': 'Pronta',
    'workout.series.lockedState': 'Bloqueada',
    'workout.series.confirmedState': 'Confirmada',
    'workout.series.lockedHint':
        'Confirme a série anterior para liberar a próxima.',
    'workout.series.weightLabel': 'Carga',
    'workout.series.repsLabel': 'Repetições',
    'workout.pr.kicker': 'NOVO RECORDE',
    'workout.pr.title': 'Você superou o seu melhor!',
    'workout.pr.volume': '{value} de volume total',
    'workout.pr.reps': '{value} repetições no total',
    'workout.tutorial.cta': 'Ver tutorial',
    'workout.tutorial.accessibilityLabel': 'Ver tutorial de {name} no YouTube',
    'workout.tutorial.errorTitle': 'Não foi possível abrir o YouTube',
    'workout.tutorial.errorMessage':
        'Confira sua conexão e tente novamente em instantes.',
    'workout.resume.title': 'Treino em andamento',
    'workout.resume.message':
        'Encontramos um treino em andamento salvo neste dispositivo. Você pode retomar de onde parou ou descartar esse rascunho.',
    'workout.resume.confirm': 'Retomar treino',
    'workout.resume.cancel': 'Descartar',
    'workout.nextMachine': 'Próxima máquina',
    'workout.replaceMachine.title': 'Substituir exercício',
    'workout.replaceMachine.confirm': 'Substituir',
    'workout.removeMachine.title': 'Remover exercício?',
    'workout.removeMachine.message':
        '"{name}" será removido apenas deste treino em andamento.',
    'workout.removeMachine.confirm': 'Remover',
    'workout.emptySession':
        'Nenhum exercício nesta sessão. Use o + para adicionar uma máquina.',
    'services.aiWorkout.generateError':
        'Não foi possível gerar o treino automaticamente',
    'services.workouts.loadError': 'Não foi possível carregar os treinos',
    'services.workouts.createError': 'Não foi possível criar o treino',
    'services.workouts.updateError': 'Não foi possível atualizar o treino',
    'services.workouts.deleteError': 'Não foi possível remover o treino',
    'services.workouts.addMachineError':
        'Não foi possível adicionar a máquina ao treino',
    'services.workouts.removeMachineError':
        'Não foi possível remover a máquina do treino',
    'services.machines.loadError': 'Não foi possível carregar as máquinas',
    'services.machines.updateError': 'Não foi possível atualizar a máquina',
    'services.history.loadError': 'Não foi possível carregar o histórico',
    'services.history.saveError': 'Não foi possível salvar o treino',
    'services.history.deleteError':
        'Não foi possível excluir o registro do histórico',
    'services.history.transferError': 'Não foi possível transferir o histórico',
    'services.credit.loadError': 'Não foi possível carregar seus créditos',
    'services.credit.checkoutError': 'Não foi possível gerar o Pix',
    'services.axios.missingApiUrl':
        'Configure EXPO_PUBLIC_API_URL no arquivo frontend/.env',
    'notifications.emulatorUnsupported':
        'Notificações não funcionam no emulador',
    'notifications.channelName': 'Lembretes de treino',
    'notifications.message1.title': 'Bora treinar! 💪',
    'notifications.message1.body':
        'Hoje é dia de {categories}. Não deixa pra amanhã!',
    'notifications.message2.title': 'Hora do ferro! 🏋️',
    'notifications.message2.body':
        'Seu treino de {categories} está te esperando.',
    'notifications.message3.title': 'Tá na hora! ⚡',
    'notifications.message3.body': 'Dia de {categories}. Bora meter carga!',
    'notifications.message4.title': 'Treino do dia 🔥',
    'notifications.message4.body':
        '{categories} no cardápio de hoje. Cola na academia!',
    'notifications.message5.title': 'Não fure o treino! 💪',
    'notifications.message5.body': 'Hoje tem {categories}. Seu corpo agradece.',
} as const
