export const ptBR = {
    "app.tagline": "Sua ficha de treino digital",
    "common.or": "ou",
    "common.actions.back": "Voltar",
    "common.actions.close": "Fechar",
    "common.actions.continue": "Continuar",
    "common.actions.enter": "Entrar",
    "common.actions.createAccount": "Criar conta",
    "common.actions.understand": "Entendi",
    "common.actions.cancel": "Cancelar",
    "common.actions.confirm": "Confirmar",
    "common.actions.add": "Adicionar",
    "common.actions.next": "Próximo",
    "common.actions.finish": "Finalizar",
    "common.actions.finishWorkout": "Finalizar treino",
    "common.actions.remove": "Remover",
    "common.actions.startWorkout": "Iniciar treino",
    "common.units.cm": "cm",
    "common.units.kg": "kg",
    "common.relative.today": "hoje",
    "common.relative.yesterday": "ontem",
    "common.relative.daysAgo": "{count} dias atrás",
    "common.relative.weekAgo": "1 semana",
    "common.relative.weeksAgo": "{count} semanas",
    "common.days.sunday": "Domingo",
    "common.days.monday": "Segunda",
    "common.days.tuesday": "Terça",
    "common.days.wednesday": "Quarta",
    "common.days.thursday": "Quinta",
    "common.days.friday": "Sexta",
    "common.days.saturday": "Sábado",
    "common.daysShort.sunday": "Dom",
    "common.daysShort.monday": "Seg",
    "common.daysShort.tuesday": "Ter",
    "common.daysShort.wednesday": "Qua",
    "common.daysShort.thursday": "Qui",
    "common.daysShort.friday": "Sex",
    "common.daysShort.saturday": "Sáb",
    "auth.login.emailLabel": "E-mail",
    "auth.login.emailPlaceholder": "seu@email.com",
    "auth.login.passwordLabel": "Senha",
    "auth.login.passwordPlaceholder": "********",
    "auth.login.submit": "Entrar",
    "auth.login.submitting": "Entrando...",
    "auth.login.forgotPasswordCta": "Esqueci minha senha",
    "auth.login.createAccountCta": "Criar conta",
    "auth.register.title": "Criar conta",
    "auth.register.subtitle": "Preencha seus dados para começar",
    "auth.register.nameLabel": "Nome",
    "auth.register.namePlaceholder": "Seu nome",
    "auth.register.emailLabel": "E-mail",
    "auth.register.emailPlaceholder": "seu@email.com",
    "auth.register.passwordLabel": "Senha",
    "auth.register.passwordPlaceholder": "Mínimo 6 caracteres",
    "auth.register.confirmPasswordLabel": "Confirmar senha",
    "auth.register.confirmPasswordPlaceholder": "Repita a senha",
    "auth.register.submit": "Criar conta",
    "auth.register.submitting": "Criando conta...",
    "auth.register.hasAccountPrefix": "Já tem conta?",
    "auth.validation.nameRequired": "Informe seu nome",
    "auth.validation.emailRequired": "Informe seu e-mail",
    "auth.validation.emailInvalid": "E-mail inválido",
    "auth.validation.passwordRequired": "Informe sua senha",
    "auth.validation.passwordCreateRequired": "Informe uma senha",
    "auth.validation.passwordMin": "Mínimo de 6 caracteres",
    "auth.validation.confirmPasswordRequired": "Confirme sua senha",
    "auth.validation.passwordMismatch": "As senhas não coincidem",
    "auth.errors.invalidCredentials": "E-mail ou senha incorretos",
    "auth.errors.emailAlreadyExists": "Este e-mail já está em uso",
    "auth.errors.emailNotVerified": "Verifique seu e-mail antes de entrar",
    "auth.errors.currentPasswordInvalid": "A senha atual está incorreta",
    "auth.errors.genericLogin": "Não foi possível entrar",
    "auth.errors.genericRegister": "Não foi possível criar a conta",
    "auth.errors.serviceUnavailableTitle": "Serviço indisponível",
    "auth.errors.serviceUnavailableMessage":
        "O serviço pode estar indisponível no momento. Tente novamente em instantes.",
    "auth.sessionExpired.title": "Sessão expirada",
    "auth.sessionExpired.message":
        "Seu acesso expirou enquanto o app estava fechado. Entre novamente para continuar.",
    "auth.resetPassword.title": "Recuperar acesso",
    "auth.resetPassword.description":
        "Informe seu e-mail e enviaremos um link para redefinir sua senha.",
    "auth.resetPassword.submit": "Enviar link",
    "auth.resetPassword.submitting": "Enviando...",
    "auth.resetPassword.successTitle": "Verifique seu e-mail",
    "auth.resetPassword.successMessage":
        "Se existir uma conta para {email}, enviaremos um link para redefinir sua senha.",
    "auth.resetPassword.error": "Não foi possível enviar o link de redefinição",
    "auth.register.successTitle": "Verifique seu e-mail",
    "auth.register.successMessage":
        "Sua conta foi criada. Enviamos um link de verificação para {email}. Depois disso, volte ao app para entrar.",
    "navigation.profile": "Perfil",
    "navigation.machineDetail": "Detalhe",
    "profile.kicker": "perfil",
    "profile.header.description":
        "Consulte os dados da conta autenticada e gerencie seu saldo de créditos para gerar treinos com IA.",
    "profile.account.title": "Conta",
    "profile.account.description": "Nome e e-mail refletem a conta autenticada no backend.",
    "profile.language.title": "Idioma do app",
    "profile.language.description":
        "Escolha o idioma padrão salvo neste dispositivo. As telas já migradas mudam na hora.",
    "profile.credits.title": "Créditos Fitcha AI",
    "profile.credits.subtitle": "1 crédito = 1 treino customizado",
    "profile.credits.description":
        "Compre créditos avulsos via Pix. O saldo é liberado automaticamente assim que o pagamento for aprovado.",
    "profile.credits.balanceLabel": "Créditos disponíveis",
    "profile.credits.balanceHint": "Cada geração concluída consome 1 crédito.",
    "profile.credits.pendingTitle": "Pagamento pendente",
    "profile.credits.pendingDescriptionWithDate":
        "Existe um Pix de {quantity} crédito(s) aguardando pagamento até {date}.",
    "profile.credits.pendingDescription":
        "Existe um Pix aguardando pagamento para liberar mais créditos.",
    "profile.credits.continuePayment": "Continuar pagamento",
    "profile.credits.buy": "Comprar créditos",
    "profile.form.title": "Segurança",
    "profile.form.description": "Altere a senha real da sua conta.",
    "profile.form.currentPasswordLabel": "Senha atual",
    "profile.form.currentPasswordPlaceholder": "Digite sua senha atual",
    "profile.form.currentPasswordRequired": "Informe sua senha atual",
    "profile.form.newPasswordRequired": "Informe uma nova senha",
    "profile.form.newPasswordLabel": "Nova senha",
    "profile.form.newPasswordPlaceholder": "Mínimo 6 caracteres",
    "profile.form.confirmNewPasswordLabel": "Confirmar nova senha",
    "profile.form.confirmNewPasswordPlaceholder": "Repita a nova senha",
    "profile.form.save": "Atualizar senha",
    "profile.form.saving": "Salvando...",
    "profile.form.saveError": "Não foi possível atualizar a senha",
    "profile.alert.savedTitle": "Senha atualizada",
    "profile.alert.savedMessage": "Sua senha foi atualizada com sucesso.",
    "creditCheckout.title": "Comprar créditos",
    "creditCheckout.description":
        "Pague via Pix e receba créditos para gerar treinos customizados com IA no Fitcha.",
    "creditCheckout.step.quantity": "Quantidade",
    "creditCheckout.step.document": "CPF",
    "creditCheckout.step.payment": "Pix",
    "creditCheckout.quantityTitle": "Quantos créditos você quer comprar?",
    "creditCheckout.quantityDescription": "Cada crédito libera 1 nova geração de treino com IA.",
    "creditCheckout.quantityLabel": "Quantidade de créditos",
    "creditCheckout.quantityPlaceholder": "1",
    "creditCheckout.quantityHint": "Cada crédito custa {price}. Total estimado: {total}.",
    "creditCheckout.documentTitle": "Informe o CPF do pagador",
    "creditCheckout.documentDescription":
        "Usamos o CPF apenas para gerar a cobrança Pix no Mercado Pago.",
    "creditCheckout.documentLabel": "CPF do pagador",
    "creditCheckout.documentPlaceholder": "00000000000",
    "creditCheckout.generatePix": "Gerar Pix",
    "creditCheckout.generatingPix": "Gerando Pix...",
    "creditCheckout.paymentFallback": "Compra de créditos Fitcha AI",
    "creditCheckout.summaryCredits": "{count} crédito(s)",
    "creditCheckout.status.paid": "Pago",
    "creditCheckout.status.awaitingPix": "Aguardando Pix",
    "creditCheckout.status.pending": "Pendente",
    "creditCheckout.pixValidUntil": "Pix válido até {date}.",
    "creditCheckout.copyPastePix": "Pix cópia e cola",
    "creditCheckout.approvedMessage":
        "Pagamento confirmado. Seus créditos já estão disponíveis no app.",
    "creditCheckout.checkPayment": "Verificar pagamento",
    "creditCheckout.openCharge": "Abrir cobrança",
    "creditCheckout.error.loadSummary": "Não foi possível carregar seus créditos",
    "creditCheckout.error.invalidQuantity": "Informe uma quantidade válida de créditos",
    "creditCheckout.error.invalidCpf": "Informe um CPF válido com 11 dígitos",
    "creditCheckout.error.generatePix": "Não foi possível gerar o Pix",
    "aiWizard.noCredits.title": "Você está sem créditos",
    "aiWizard.noCredits.description":
        "Cada treino gerado com IA consome 1 crédito. Compre créditos para continuar.",
    "aiWizard.noCredits.buy": "Comprar créditos",
    "categories.peito": "Peito",
    "categories.costas": "Costas",
    "categories.pernas": "Pernas",
    "categories.ombros": "Ombros",
    "categories.biceps": "Bíceps",
    "categories.triceps": "Tríceps",
    "categories.core": "Core",
    "categories.cardio": "Cardio",
    "addMachine.title": "Nova máquina",
    "addMachine.nameLabel": "nome",
    "addMachine.namePlaceholder": "Ex.: supino reto",
    "addMachine.descriptionLabel": "descrição (opcional)",
    "addMachine.descriptionPlaceholder": "Detalhes sobre o exercício...",
    "addMachine.categoryLabel": "categoria",
    "addMachine.allCategories": "todas",
    "addMachine.searchLabel": "buscar",
    "addMachine.searchPlaceholder": "Digite o nome ou apelido da máquina",
    "addMachine.loading": "Carregando catálogo...",
    "addMachine.emptyTitle": "Nenhuma máquina encontrada",
    "addMachine.emptyMessage": "Tente outro nome ou ajuste o filtro de categoria.",
    "week.title": "Sua semana",
    "week.todayBadge": "HOJE",
    "week.emptyDay": "Nenhuma máquina planejada ainda.",
    "week.machineCount": "{count} máquina{pluralSuffix}",
    "week.generated.title": "Treino gerado",
    "week.generated.message":
        "Seu treino automático foi criado com sucesso e substituiu a semana atual.",
    "day.machineCount": "{count} máquina{pluralSuffix}",
    "day.addButton": "Adicionar máquina",
    "day.maxWeight": "máx. {weight}kg",
    "day.remove.title": "Remover máquina",
    "day.remove.message":
        'Remover "{name}" deste dia? O histórico será mantido se ela estiver em outro dia.',
    "detail.permission.title": "Permissão necessária",
    "detail.permission.galleryMessage":
        "Permita acesso à galeria para selecionar uma foto da máquina.",
    "detail.permission.cameraMessage":
        "Permita acesso à câmera para registrar uma foto da máquina.",
    "detail.photo.add": "Adicionar foto",
    "detail.photo.change": "Trocar foto",
    "detail.photo.sourceMessage": "Escolha de onde a imagem deve vir.",
    "detail.photo.useCamera": "Usar câmera",
    "detail.photo.chooseGallery": "Escolher da galeria",
    "detail.photo.removeTitle": "Remover foto?",
    "detail.photo.removeMessage": "A imagem atual será removida desta máquina.",
    "detail.photo.removeAction": "Remover foto",
    "detail.photo.actionsTitle": "Foto da máquina",
    "detail.photo.actionsMessage": "Escolha o que deseja fazer com a imagem.",
    "detail.record.title": "recorde",
    "detail.record.subtitle": "Sequência com maior volume já salva nessa máquina.",
    "detail.record.empty": "Ainda não há recorde salvo para essa máquina.",
    "detail.record.volume": "volume {volume}",
    "detail.history.title": "histórico",
    "detail.history.empty":
        "Nenhum registro ainda. Inicie um treino para registrar pesos e repetições.",
    "home.greetingFallback": "atleta",
    "home.delta.noBase": "Sem base",
    "home.delta.zero": "0 kg",
    "home.relative.daysAgo": "{count} dias",
    "home.featured.emptyTitle": "evolução por máquina",
    "home.featured.emptySubtitle": "Monte a semana para destravar essa comparação por exercício.",
    "home.featured.todayTitle": "máquinas de hoje",
    "home.featured.todaySubtitle":
        "Arraste para o lado e veja a evolução de carga em cada máquina.",
    "home.featured.nextTitle": "próximo treino - {day}",
    "home.featured.nextSubtitle":
        "Hoje não há máquinas planejadas, então a comparação usa o próximo dia ativo.",
    "home.featured.focusCount": "{count} máquina{pluralSuffix} em foco",
    "home.featured.noPlannedDays": "Nenhum dia planejado ainda",
    "home.featured.emptyPanel":
        "Abra a Week, distribua as máquinas nos dias da semana e esta área passa a mostrar a evolução de cada uma.",
    "home.machine.comparison.noHistory": "Ainda não existe treino salvo nessa máquina.",
    "home.machine.comparison.needMore": "Salve mais um treino para comparar a evolução.",
    "home.machine.comparison.default":
        "Comparação da carga atual contra o primeiro registro salvo.",
    "home.machine.previous.noHistory": "sem histórico",
    "home.machine.previous.oneRecord": "1 registro salvo",
    "home.machine.previous.noComparison": "sem comparação",
    "home.machine.previous.vsLast": "{value} vs. último treino",
    "home.machine.lastTrained": "último {label}",
    "home.machine.noTraining": "sem treino",
    "home.machine.metric.current": "atual",
    "home.machine.metric.initial": "inicial",
    "home.machine.metric.record": "recorde",
    "home.machine.recordVolume": "{volume} de volume",
    "home.machine.noHistoryCard":
        "Essa máquina já está no dia planejado, mas ainda não tem histórico salvo.",
    "home.machine.recordsTitle": "últimos registros",
    "home.header.kicker": "painel inicial",
    "home.header.greeting": "Olá, {name}",
    "home.header.summaryWithHistory":
        "Sequência atual de {streak} dia{streakSuffix} e {recent} dia{recentSuffix} ativo{activeSuffix} nos últimos 7 dias.",
    "home.header.summaryWithoutHistory":
        "Sua semana já pode ser organizada aqui, mas a análise fica muito melhor depois do primeiro treino salvo.",
    "home.header.lastWorkout": "último treino",
    "home.header.nextTarget": "próximo alvo",
    "home.header.noRecord": "sem registro",
    "home.header.buildWeek": "monte sua semana",
    "home.header.openWeek": "Abrir semana",
    "home.stats.streakTitle": "Sequência",
    "home.stats.streakHint": "dias seguidos{suffix}",
    "home.stats.streakHintZero": " por enquanto",
    "home.stats.last7Title": "Últimos 7 dias",
    "home.stats.last7Hint": "dias com treino salvo",
    "home.stats.monthTitle": "No mês",
    "home.stats.monthHint": "dias indo para a academia",
    "home.stats.weekTitle": "Semana",
    "home.stats.weekHint": "{count} máquina{pluralSuffix} planejada{pluralSuffix}",
    "home.rhythm.kicker": "ritmo da semana",
    "home.rhythm.titleWithCount": "{count} dia{daySuffix} já montado{builtSuffix}",
    "home.rhythm.titleEmpty": "Sua semana ainda está vazia",
    "home.rhythm.subtitleWithNext": "Próximo compromisso: {next}.",
    "home.rhythm.subtitleEmpty":
        "Abra a Week para montar os dias, máquinas e categorias que quer seguir.",
    "home.nextPlanned.today": "Hoje - {count} máquina{pluralSuffix}",
    "home.nextPlanned.tomorrow": "Amanhã - {count} máquina{pluralSuffix}",
    "home.nextPlanned.other": "{day} - {count} máquina{pluralSuffix}",
    "aiWizard.badge": "treino com IA",
    "aiWizard.step.body": "Seus dados físicos",
    "aiWizard.step.days": "Quais dias você vai treinar?",
    "aiWizard.step.preferences": "Preferências do treino",
    "aiWizard.step.intensity": "Qual a intensidade?",
    "aiWizard.step.goal": "Qual é o seu objetivo?",
    "aiWizard.step.instructions": "Instruções personalizadas",
    "aiWizard.step.review": "Confirmar geração",
    "aiWizard.actions.generate": "Gerar treino",
    "aiWizard.actions.generating": "Gerando...",
    "aiWizard.error.title": "Erro ao gerar treino",
    "aiWizard.error.message": "Não foi possível gerar o treino agora.",
    "aiWizard.body.heightLabel": "Altura (cm)",
    "aiWizard.body.weightLabel": "Peso (kg)",
    "aiWizard.body.hint": "Esses dados ajudam a calibrar os pesos sugeridos.",
    "aiWizard.days.description":
        "Marque exatamente os dias em que você quer ir para a academia. A IA vai usar isso para montar a divisão com mais precisão.",
    "aiWizard.days.empty": "Selecione pelo menos um dia.",
    "aiWizard.days.selectedCount": "{count} dia{daySuffix} selecionado{selectedSuffix}.",
    "aiWizard.preferences.description":
        "Esses campos são opcionais. Preencha se quiser que a IA respeite um limite de tempo, volume diário ou um modelo de divisão específico.",
    "aiWizard.preferences.hoursLabel": "Horas por dia",
    "aiWizard.preferences.hoursPlaceholder": "Ex.: 1, 1.5 ou 2",
    "aiWizard.preferences.machinesLabel": "Máquinas por dia",
    "aiWizard.preferences.machinesPlaceholder": "Ex.: 6",
    "aiWizard.preferences.splitLabel": "Modelo de divisão",
    "aiWizard.preferences.splitPlaceholder": "Ex.: ABC, ABCAB, fullbody",
    "aiWizard.intensity.light.title": "leve",
    "aiWizard.intensity.light.description": "Iniciante ou retorno",
    "aiWizard.intensity.moderate.title": "moderado",
    "aiWizard.intensity.moderate.description": "Treino consistente",
    "aiWizard.intensity.intense.title": "intenso",
    "aiWizard.intensity.intense.description": "Alto volume e carga",
    "aiWizard.goal.hypertrophy.title": "hipertrofia",
    "aiWizard.goal.hypertrophy.description": "Ganho de massa muscular",
    "aiWizard.goal.strength.title": "força",
    "aiWizard.goal.strength.description": "Aumento de carga máxima",
    "aiWizard.goal.endurance.title": "resistência",
    "aiWizard.goal.endurance.description": "Mais repetições e stamina",
    "aiWizard.goal.weightLoss.title": "emagrecimento",
    "aiWizard.goal.weightLoss.description": "Perda de gordura com treino",
    "aiWizard.instructions.description":
        "Adicione observações para a IA, como lesões, exercícios que você prefere evitar, foco em algum grupo muscular ou equipamentos que a academia tem.",
    "aiWizard.instructions.placeholder":
        "Ex.: evitar agachamento livre por dor no joelho e priorizar máquinas.",
    "aiWizard.review.title": "resumo da geração",
    "aiWizard.review.height": "Altura",
    "aiWizard.review.weight": "Peso",
    "aiWizard.review.selectedDays": "Dias escolhidos",
    "aiWizard.review.totalDays": "Total de dias",
    "aiWizard.review.hoursPerDay": "Horas por dia",
    "aiWizard.review.machinesPerDay": "Máquinas por dia",
    "aiWizard.review.split": "Modelo de divisão",
    "aiWizard.review.intensity": "Intensidade",
    "aiWizard.review.goal": "Objetivo",
    "aiWizard.review.instructions": "Instruções personalizadas",
    "aiWizard.review.notInformed": "Não informado",
    "aiWizard.review.noSpecificSplit": "Nenhum modelo específico",
    "aiWizard.review.noAdditionalNotes": "Nenhuma observação adicional.",
    "aiWizard.review.promptNote":
        "O prompt final agora é montado somente no backend antes de chamar a IA.",
    "workout.saved.title": "Treino finalizado!",
    "workout.saved.message":
        "{count} máquina{machineSuffix} registrada{registeredSuffix} em {elapsed}",
    "workout.empty.title": "Treino vazio",
    "workout.empty.message": "Nenhuma série foi registrada.",
    "workout.error.title": "Erro ao salvar",
    "workout.error.message":
        "Não foi possível salvar o treino agora. Tente novamente em instantes.",
    "workout.incomplete.title": "Nenhuma máquina completa",
    "workout.incomplete.message":
        "Ainda não há exercício com as 3 séries completas. Se sair agora, os rascunhos serão descartados.",
    "workout.incomplete.confirm": "Sair sem salvar",
    "workout.pending.title": "Finalizar com pendências?",
    "workout.pending.message":
        "{count} máquina{machineSuffix} sem as 3 séries completas. Você pode salvar agora ou continuar revisando.",
    "workout.quit.title": "Encerrar treino?",
    "workout.quit.message": "Se você sair agora, o treino será encerrado e nada será salvo.",
    "workout.quit.confirm": "Encerrar",
    "workout.series.one": "Série 1",
    "workout.series.two": "Série 2",
    "workout.series.three": "Série 3",
    "workout.position": "{current} de {total}",
    "workout.completedProgress": "{completed}/{total} completas",
    "workout.swapHint":
        "Use as setas ou toque nos cartões para trocar de máquina sem perder os rascunhos.",
    "workout.status.registeredTitle": "Exercício registrado",
    "workout.status.draftTitle": "Rascunho salvo",
    "workout.status.skipTitle": "Pode pular sem perder o fluxo",
    "workout.status.registeredMessage":
        "Você pode seguir adiante ou voltar depois para ajustar os pesos.",
    "workout.status.draftMessage":
        "Os valores ficam guardados ao trocar de máquina. Complete quando ela estiver livre.",
    "workout.status.skipMessage":
        "Se a máquina estiver ocupada, avance agora e volte quando quiser pelos cartões acima.",
    "workout.rest.title": "descanso",
    "workout.rest.idle": "O timer começa assim que você confirmar uma série.",
    "workout.rest.active": "Contando desde a última série confirmada.",
    "workout.fillSeries": "preencha carga e repetições nas 3 séries",
    "workout.series.confirmCta": "Confirmar",
    "workout.series.confirmedCta": "Confirmada",
    "workout.series.readyState": "Pronta",
    "workout.series.lockedState": "Bloqueada",
    "workout.series.confirmedState": "Confirmada",
    "workout.series.lockedHint": "Confirme a série anterior para liberar a próxima.",
    "workout.series.weightLabel": "Carga",
    "workout.series.repsLabel": "Repetições",
    "workout.nextMachine": "Próxima máquina",
    "services.aiWorkout.generateError": "Não foi possível gerar o treino automaticamente",
    "services.days.loadError": "Não foi possível carregar os dias",
    "services.days.addError": "Não foi possível adicionar a máquina",
    "services.days.removeError": "Não foi possível remover a máquina",
    "services.days.replaceError": "Não foi possível substituir a semana",
    "services.machines.loadError": "Não foi possível carregar as máquinas",
    "services.machines.updateError": "Não foi possível atualizar a máquina",
    "services.history.loadError": "Não foi possível carregar o histórico",
    "services.history.saveError": "Não foi possível salvar o treino",
    "services.credit.loadError": "Não foi possível carregar seus créditos",
    "services.credit.checkoutError": "Não foi possível gerar o Pix",
    "services.axios.missingApiUrl": "Configure EXPO_PUBLIC_API_URL no arquivo frontend/.env",
    "notifications.emulatorUnsupported": "Notificações não funcionam no emulador",
    "notifications.channelName": "Lembretes de treino",
    "notifications.message1.title": "Bora treinar! 💪",
    "notifications.message1.body": "Hoje é dia de {categories}. Não deixa pra amanhã!",
    "notifications.message2.title": "Hora do ferro! 🏋️",
    "notifications.message2.body": "Seu treino de {categories} está te esperando.",
    "notifications.message3.title": "Tá na hora! ⚡",
    "notifications.message3.body": "Dia de {categories}. Bora meter carga!",
    "notifications.message4.title": "Treino do dia 🔥",
    "notifications.message4.body": "{categories} no cardápio de hoje. Cola na academia!",
    "notifications.message5.title": "Não fure o treino! 💪",
    "notifications.message5.body": "Hoje tem {categories}. Seu corpo agradece.",
} as const;
